const fs = require('fs');
const path = require('path');

const n5 = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/kanji/n5.json'), 'utf8'));
const n4 = JSON.parse(fs.readFileSync(path.join(__dirname, '../data/kanji/n4.json'), 'utf8'));

const globalSeen = new Set([...n5.map(x => x.k), ...n4.map(x => x.k)]);

// Helper to add clean items
function makeBuilder(level, targetMin) {
  const items = [];
  const levelSeen = new Set();

  return {
    add(k, h, r, m, ex, s_jp, s_hira, s_en) {
      if (globalSeen.has(k) || levelSeen.has(k)) return;
      globalSeen.add(k);
      levelSeen.add(k);
      items.push({
        k, lvl: level, h, r, m, ex, s_jp, s_hira, s_en,
        source: "JLPT-aligned Study Reference"
      });
    },
    save(filename) {
      console.log(`[${level}] Compiled ${items.length} records (target was >= ${targetMin})`);
      fs.writeFileSync(path.join(__dirname, `../data/kanji/${filename}`), JSON.stringify(items, null, 2), 'utf8');
      return items.length;
    }
  };
}

// ----------------------------------------------------
// N3 BUILDER
// ----------------------------------------------------
const n3 = makeBuilder('N3', 150);

const n3Master = [
  ["政", "セイ、ショウ / まつりごと", "sei, shou / matsurigoto", "politics, government", "政治 (seiji - politics)", "国の政治に関心を持つ。", "くにのせいじにかんしんをもつ。", "Take interest in national politics."],
  ["経", "ケイ、キョウ / へ・る", "kei, kyou / he-ru", "pass through, manage, longitude", "経済 (keizai - economy)", "世界経済の動向を調べる。", "せかいけいざいのどうこうをしらべる。", "Investigate trends in the world economy."],
  ["済", "サイ、ザイ / す・む、す・ます", "sai, zai / su-mu, su-masu", "settle, relieve, finish", "経済 (keizai - economy)", "支払いを手早く済ませる。", "しはらいをとばやくすませる。", "Finish payments quickly."],
  ["歴", "レキ", "reki", "curriculum, passage of time", "歴史 (rekishi - history)", "日本の古代歴史を学ぶ。", "にほんのこだいれきしをまなぶ。", "Study ancient Japanese history."],
  ["史", "シ", "shi", "history, chronicle", "歴史 (rekishi - history)", "近代史の講義を聴く。", "きんだいしのこうぎをきく。", "Listen to a lecture on modern history."],
  ["育", "イク / そだ・つ、そだ・てる", "iku / soda-tsu, soda-teru", "bring up, grow up, educate", "教育 (kyouiku - education)", "子どもを健やかに育てる。", "こどもをすこやかにそだてる。", "Raise children healthily."],
  ["化", "カ、ケ / ば・ける、ば・かす", "ka, ke / ba-keru, ba-kasu", "change, take form of, influence", "文化 (bunka - culture)", "伝統文化を大切に守る。", "でんとうぶんかをたいせつにまもる。", "Carefully protect traditional culture."],
  ["際", "サイ / きわ", "sai / kiwa", "occasion, side, edge", "国際 (kokusai - international)", "国際交流イベントに参加する。", "こくさいこうりゅういべんとにかんかする。", "Participate in an international exchange event."],
  ["科", "カ", "ka", "department, course, science", "科学 (kagaku - science)", "最新の科学技術を導入する。", "さいしんのかがくぎじゅつをどうにゅうする。", "Introduce the latest scientific technology."],
  ["数", "スウ、ス / かず、かぞ・える", "suu, su / kazu, kazo-eru", "number, count", "数字 (suuji - number, digit)", "参加者の数を数える。", "さんかしゃのかずをかぞえる。", "Count the number of participants."],
  ["記", "キ / しる・す", "ki / shiru-su", "scribe, account, narrate", "記録 (kiroku - record)", "日々の出来事をノートに記録する。", "ひびのできごとをのーとにきろくする。", "Record daily events in a notebook."],
  ["法", "ホウ、ハッ、ホッ", "hou, hatsu, hotsu", "law, rule, method", "法律 (houritsu - law)", "法律を守ることは国民の義務だ。", "ほうりつをまもることはこくみんのぎむだ。", "Obeying the law is a citizen's duty."],
  ["律", "リツ、リチ", "ritsu, richi", "rhythm, law, regulation", "規律 (kiritsu - discipline)", "規律正しい生活習慣を送る。", "きりつただしいせいかつしゅうかんをおくる。", "Lead well-disciplined lifestyle habits."],
  ["制", "セイ", "sei", "system, control, rule", "制度 (seido - system)", "新しい評価制度を導入する。", "あたらしいひょうかせいどをどうにゅうする。", "Introduce a new evaluation system."],
  ["務", "ム / つと・める", "mu / tsuto-meru", "task, duties", "義務 (gimu - duty, obligation)", "公務員の職務を全うする。", "こうむいんのしょくむをまっとうする。", "Fulfill the duties of a public servant."],
  ["役", "ヤク、エキ", "yaku, eki", "duty, role, service", "主役 (shuyaku - leading role)", "舞台で主役を立派に演じる。", "ぶたいでしゅやくをりっぱにえんじる。", "Splendidly perform the lead role on stage."],
  ["協", "キョウ", "kyou", "co-operation", "協力 (kyouryoku - cooperation)", "全員でお互いに協力し合う。", "ぜんいんでおたがいにきょうりょくしあう。", "Everyone cooperates with each other."],
  ["結", "ケツ / むす・ぶ、ゆ・う", "ketsu / musu-bu, yu-u", "tie, bind, conclude", "結果 (kekka - result)", "努力が良い結果を生んだ。", "どりょくがよいけっかをうんだ。", "Effort produced a good result."],
  ["相", "ソウ、ショウ / あい", "sou, shou / ai", "mutual, minister, aspect", "相談 (soudan - consultation)", "相手の目を見て誠実に話す。", "あいてのめをみてせいじつにはなす。", "Speak sincerely while looking at the other person's eyes."],
  ["談", "ダン", "dan", "discuss, talk", "面談 (mendan - interview)", "進路について先生と面談する。", "しんろについてせんせいとめんだんする。", "Have an interview with the teacher about career path."],
  ["関", "カン / せき、かか・わる", "kan / seki, kaka-waru", "connection, gateway, involve", "関係 (kankei - relation)", "環境問題に強い関心を持つ。", "かんきょうもんだいにつよいかんしんをもつ。", "Have strong interest in environmental problems."],
  ["係", "ケイ / かか・る、かかり", "kei / kaka-ru, kakari", "person in charge, connection", "案内係 (annaigakari - guide)", "係の指示に従って整列する。", "かかりのしじにしたがってせいれつする。", "Line up according to the staff's instructions."],
  ["連", "レン / つ・れる、つら・なる", "ren / tsu-reru, tsura-naru", "take along, lead, join", "連絡 (renraku - contact)", "友達を連れて美術館へ行く。", "ともだちをつれてびじゅつかんへいく。", "Take a friend along to the art museum."],
  ["絡", "ラク / から・む、から・まる", "raku / kara-mu, kara-maru", "entangle, twine, connect", "連絡 (renraku - communication)", "後ほどメールで連絡いたします。", "のちほどめーるでれんらくいたします。", "I will contact you by email later."],
  ["由", "ユ、ユウ / よし", "yu, yuu / yoshi", "reason, cause", "自由 (jiyuu - freedom)", "遅刻の理由を丁寧に話す。", "ちこくのりゆうをていねいにはなす。", "Politely explain the reason for being late."],
  ["報", "ホウ / むく・いる", "hou / muku-iru", "report, news, reward", "報告 (houkoku - report)", "天気予報を確認して傘を持つ。", "てんきよほうをかくにんしてかさをもつ。", "Check the weather forecast and take an umbrella."],
  ["告", "コク / つ・げる", "koku / tsu-geru", "inform, declare, tell", "広告 (koukoku - advertisement)", "新製品の広告を雑誌に出す。", "しんせいひんのこうこくをざっしにだす。", "Place a new product advertisement in a magazine."],
  ["求", "キュウ / もと・める", "kyuu / moto-meru", "request, want, seek", "要求 (youkyuu - demand)", "平和な社会を心から求める。", "へいわなしゃかいをこころからもとめる。", "Seek a peaceful society from the heart."],
  ["期", "キ、ゴ", "ki, go", "period, time, date", "期間 (kikan - period)", "試験の期日が次第に近づく。", "しけんのきじつがしだいにちかづく。", "The exam date gradually approaches."],
  ["限", "ゲン / かぎ・る", "gen / kagi-ru", "limit, restrict", "限界 (genkai - limit)", "時間には限りがあるため急ぐ。", "じかんにはかぎりがあるためいそぐ。", "Hurry because time has a limit."],
  ["基", "キ / もと、もとい", "ki / moto, motoi", "fundamentals, base", "基本 (kihon - foundation)", "文法の基本をしっかり身につける。", "ぶんぽうのきほんをしっかりみにつける。", "Firmly master the basics of grammar."],
  ["準", "ジュン", "jun", "semi-, associate, standard", "準備 (junbi - preparation)", "標準的な手順に従い作業する。", "ひょうじゅんてきなてじゅんにしたがいさぎょうする。", "Work following standard procedures."],
  ["備", "ビ / そな・える、そな・わる", "bi / sona-eru, sona-waru", "equip, provision, prepare", "準備 (junbi - preparation)", "自然災害に備えて非常食を用意する。", "しぜんさいがいにそなえてひじょうしょくをよういする。", "Prepare emergency food in preparation for natural disasters."],
  ["調", "チョウ / しら・べる、ととの・う", "chou / shira-beru, totono-u", "tune, tone, investigate", "調査 (chousa - survey)", "辞書で単語の意味を詳しく調べる。", "じしょでたんごのいみをくわしくしらべる。", "Look up word meanings in detail using a dictionary."],
  ["査", "サ", "sa", "investigate, examine", "審査 (shinsa - judging, inspection)", "パスポートの入国審査を受ける。", "ぱすぽーとのにゅうこくしんさをうける。", "Undergo passport entry inspection."],
  ["約", "ヤク", "yaku", "promise, approximately", "約束 (yakusoku - promise)", "約一時間歩いて駅に着いた。", "やくいちじかんあるいてえきについた。", "Arrived at the station after walking for approximately one hour."],
  ["束", "ソク / たば、たば・ねる", "soku / taba, taba-neru", "bundle, sheath, bind", "花束 (hanataba - bouquet)", "感謝の花束を先生に贈る。", "かんしゃのはなたばをせんせいにおくる。", "Gift a bouquet of flowers in gratitude to the teacher."],
  ["必", "ヒツ / かなら・ず", "hitsu / kanara-zu", "invariable, certain, inevitable", "必要 (hitsuyou - necessary)", "必ず夢を叶えると誓う。", "かならずゆめをかなえるとちかう。", "Vow to definitely make dreams come true."],
  ["要", "ヨウ / い・る、かなめ", "you / i-ru, kaname", "need, vital point", "重要 (juuyou - important)", "重要な書類を金庫に保管する。", "じゅうようなしょるいをきんこにほかんする。", "Store important documents in a safe."],
  ["想", "ソウ、ソ / おも・う", "sou, so / omo-u", "concept, think, idea", "想像 (souzou - imagination)", "未来の平和な世界を想う。", "みらいのへいわなせかいをおもう。", "Envision a peaceful future world."],
  ["像", "ゾウ", "zou", "statue, picture, image", "映像 (eizou - video, image)", "高画質な映像を楽しむ。", "こうがしつなえいぞうをたのしむ。", "Enjoy high-definition video."],
  ["受", "ジュ / う・ける、う・かる", "ju / u-keru, u-karu", "accept, undergo, catch", "受験 (juken - taking exam)", "希望の学校を受験する。", "きぼうのがっこうをじゅけんする。", "Take entrance exams for the desired school."],
  ["付", "フ / つ・ける、つ・く", "fu / tsu-keru, tsu-ku", "adhere, attach, append", "受付 (uketsuke - reception)", "名札を胸のポケットに付ける。", "なふだをむねのぽけっとにつける。", "Attach the name badge to the chest pocket."],
  ["解", "カイ、ゲ / と・く、と・ける", "kai, ge / to-ku, to-keru", "unravel, notes, solve", "解決 (kaiketsu - solution)", "複雑なパズルを解く。", "ふくざつなぱずるをとく。", "Solve a complex puzzle."],
  ["説", "セツ / と・く", "setsu / to-ku", "opinion, theory, explain", "説明 (setsumei - explanation)", "問題の解き方を分かりやすく説明する。", "もんだいのときかたをわかりやすくせつめいする。", "Explain how to solve the problem clearly."],
  ["向", "コウ / む・く、む・ける", "kou / mu-ku, mu-keru", "yonder, face, turn toward", "方向 (houkou - direction)", "前をしっかり向いて進む。", "まえをしっかりむいてすすむ。", "Advance looking straight ahead."],
  ["進", "シン / すす・む、すす・める", "shin / susu-mu, susu-meru", "advance, proceed, progress", "進歩 (shinpo - progress)", "毎日一歩ずつ前に進む。", "まいにちいっぽずつまえにすすむ。", "Move forward one step at a time every day."],
  ["退", "タイ / しりぞ・く", "tai / shirizo-ku", "retreat, withdraw, resign", "引退 (intai - retirement)", "現役選手を引退する。", "げんえきせんしゅをいんたいする。", "Retire as an active athlete."],
  ["返", "ヘン / かえ・す、かえ・る", "hen / kae-su, kae-ru", "return, answer, fade", "返事 (henji - reply)", "本を図書館のカウンターに返す。", "ほんをとしょかんのかうんたーにかえす。", "Return the book to the library counter."],
  ["客", "キャク、カク", "kyaku, kaku", "guest, visitor, customer", "乗客 (joukyaku - passenger)", "大切なお客様を笑顔で迎える。", "たいせつなおきゃくさまをえがおでむかえる。", "Welcome important customers with a smile."],
  ["席", "セキ / むしろ", "seki / mushiro", "seat, mat, occasion", "指定席 (shiteiseki - reserved seat)", "新幹線の指定席を予約する。", "しんかんせんのしていせきをよやくする。", "Reserve a reserved seat on the Shinkansen."],
  ["勝", "ショウ / か・つ、まさ・る", "shou / ka-tsu, masa-ru", "victory, win, excel", "勝利 (shouri - victory)", "決勝戦で最後まで戦い勝つ。", "けっしょうせんでさいごまでたたかいかつ。", "Fight until the end and win in the final."],
  ["負", "フ / ま・ける、お・う", "fu / ma-keru, o-u", "lose, owe, assume", "勝負 (shoubu - match)", "負けても諦めずに再挑戦する。", "まけてもあきらめずにさいちょうせんする。", "Retry without giving up even if losing."],
  ["争", "ソウ / あらそ・う", "sou / arasou", "contend, dispute, argue", "競争 (kyousou - competition)", "無駄な争いを避けて話し合う。", "むだなあらそいをさけてはなしあう。", "Avoid pointless disputes and talk it through."],
  ["戦", "セン / たたか・う", "sen / tataka-u", "war, battle, match", "作戦 (sakusen - tactics)", "困難な壁に勇敢に立ち向かい戦う。", "こんなんなかべにゆうかんにたちむかいたたかう。", "Bravely face and fight against difficult barriers."],
  ["初", "ショ / はじ・め、はつ", "sho / haji-me, hatsu", "first time, beginning", "初心 (shoshin - original intention)", "初級から上級まで段階的に学ぶ。", "しょきゅうからじょうきゅうまでだんかいてきにまなぶ。", "Learn step by step from beginner to advanced."],
  ["終", "シュウ / お・わる、お・える", "shuu / o-waru, o-eru", "end, finish", "最終 (saishuu - final)", "本日の講義が無事に終わった。", "ほんじつのこうぎがぶじにおわった。", "Today's lecture safely finished."],
  ["最", "サイ / もっと・も", "sai / motto-mo", "utmost, most, extreme", "最高 (saikou - best, supreme)", "世界で最も美しい景色を眺める。", "せかいでもっともうつくしいけしきをながめる。", "Gaze upon the most beautiful scenery in the world."],
  ["級", "キュウ", "kyuu", "class, rank, grade", "学級 (gakkyuu - school class)", "日本語能力試験でN3級に合格する。", "にほんごのうりょくしけんでN3きゅうにごうかくする。", "Pass JLPT N3 level certification."],
  ["比", "ヒ / くら・べる", "hi / kura-beru", "compare, race, ratio", "比較 (hikaku - comparison)", "二つの製品の性能を比べる。", "ふたつのせいひんのせいのうをくらべる。", "Compare the performance of the two products."],
  ["較", "カク", "kaku", "contrast, compare", "比較 (hikaku - comparison)", "価格と品質を比較検討する。", "かかくとひんしつをひかくけんとうする。", "Compare and evaluate price and quality."],
  ["点", "テン / つ・ける", "ten / tsu-keru", "point, dot, mark", "満点 (manten - perfect score)", "小テストで満点を取る。", "しょうてすとでまんてんをとる。", "Get a perfect score on the quiz."],
  ["直", "チョク、ジキ / ただ・ちに、なお・す", "choku, jiki / tada-chini, nao-su", "straight, fix, direct", "直接 (chokusetsu - direct)", "壊れた時計を丁寧に直す。", "こわれたとけいにていねいになおす。", "Carefully repair the broken clock."],
  ["接", "セツ / つ・ぐ", "setsu / tsu-gu", "touch, contact, join", "面接 (mensetsu - interview)", "就職試験の面接に臨む。", "しゅうしょくしけんのめんせつにのぞむ。", "Attend the job examination interview."],
  ["面", "メン / おもて、つら", "men / omote, tsura", "mask, face, aspect", "正面 (shoumen - front)", "建物の正面玄関に集合する。", "たてもののしょうめんげんかんにしゅうごうする。", "Gather at the front entrance of the building."],
  ["反", "ハン / そ・る、かえ・す", "han / so-ru, kae-su", "anti-, bend, oppose", "違反 (ihan - violation)", "交通ルールに違反しない。", "こうつうるーるにいはんしない。", "Do not violate traffic rules."],
  ["対", "タイ、ツイ", "tai, tsui", "vis-a-vis, opposite, pair", "対話 (taiwa - dialogue)", "相手に対して敬意を持って接する。", "あいてにたいしてけいいをもってせっする。", "Interact with respect toward the other person."],
  ["側", "ソク / かわ、そば", "soku / kawa, soba", "side, lean, oppose", "両側 (ryougawa - both sides)", "川の両側に桜の木が並ぶ。", "かわのりょうがわにさくらのきがならぶ。", "Cherry trees line both sides of the river."],
  ["投", "トウ / な・げる", "tou / na-geru", "throw, discard, invest", "投資 (toushi - investment)", "未来のために自己投資を行う。", "みらいのためにじことうしをおこなう。", "Make self-investments for the future."],
  ["票", "ヒョウ", "hyou", "ballot, label, ticket", "投票 (touhyou - voting)", "大切な一票を清き心で投じる。", "たいせつないっぴょうをきよきこころでとうじる。", "Cast an important vote with a clear conscience."],
  ["選", "セン / えら・ぶ", "sen / era-bu", "elect, choose, select", "選択 (sentaku - choice)", "自分にとって最良の進路を選ぶ。", "じぶんにとってさいりょうのしんろをえらぶ。", "Choose the best path for oneself."],
  ["挙", "キョ / あ・げる", "kyo / a-geru", "raise, plan, actions", "選挙 (senkyo - election)", "質問があるときは手を挙げる。", "しつもんがあるときはてをあげる。", "Raise hand when you have a question."],
  ["包", "ホウ / つつ・む", "hou / tsutsu-mu", "wrap, pack, cover", "包装 (housou - wrapping)", "贈り物を綺麗な和紙で包む。", "おくりものをきれいなわしでつつむ。", "Wrap the gift in beautiful Japanese paper."],
  ["装", "ソウ / よそお・う", "sou / yosoo-u", "attire, dress, equip", "服装 (fukusou - garments)", "面接には清潔な服装で臨む。", "めんせつにはせいけつなふくそうでぞむ。", "Attend the interview in neat, clean clothes."],
  ["展", "テン", "ten", "unfold, expand", "発展 (hatten - development)", "科学技術が急速に発展する。", "かがくぎじゅつがきゅうそくにはってんする。", "Science and technology develop rapidly."],
  ["示", "ジ、シ / しめ・す", "ji, shi / shime-su", "show, indicate, point out", "提示 (teiji - presentation)", "身分証明書を受付で提示する。", "みぶんしょうめいしょをうけつけでていじする。", "Present identification at the reception desk."],
  ["存", "ソン、ゾン", "son, zon", "exist, know, suppose", "生存 (seizon - survival)", "ご存知の通り計画は順調です。", "ごぞんじのとおりけいかくはじゅんちょうです。", "As you know, the plan is on track."],
  ["在", "ザイ / あ・る", "zai / a-ru", "exist, located in", "存在 (sonzai - existence)", "家族の存在が大きな支えになる。", "かぞくのそんざいがおおきなささえになる。", "The presence of family is a great support."],
  ["現", "ゲン / あらわ・れる", "gen / arawa-reru", "present, existing, appear", "現在 (genzai - present time)", "現在地をスマートフォンで確認する。", "げんざいちをすまーとふぉんでかくにんする。", "Check the current location on the smartphone."],
  ["組", "ソ / く・む、くみ", "so / ku-mu, kumi", "association, assemble, braid", "番組 (bangumi - program)", "テレビで教育番組を見る。", "てれびできょういくばんぐみをみる。", "Watch an educational program on television."],
  ["織", "ショク / お・る", "shoku / o-ru", "weave, fabric", "組織 (soshiki - organization)", "伝統的な技法で布を織る。", "でんとうてきなぎほうでぬのをおる。", "Weave cloth using traditional techniques."],
  ["変", "ヘン / か・わる、か・える", "hen / ka-waru, ka-eru", "unusual, change, strange", "大変 (taihen - tough, very)", "生活環境が大きく変わる。", "せいかつかんきょうがおおきくかわる。", "Living environment changes greatly."],
  ["信", "シン", "shin", "faith, trust, message", "信用 (shin'you - trust)", "仲間との信頼関係を築く。", "なかまとのしんらいかんけいをきずく。", "Build relations of trust with peers."],
  ["号", "ゴウ", "gou", "nickname, number, item", "番号 (bangou - number)", "電話番号をメモ帳に控える。", "でんわばんごうをめもちょうにひかえる。", "Take note of the phone number in the memo pad."],
  ["置", "チ / お・く", "chi / o-ku", "placement, put, establish", "位置 (ichi - location)", "荷物を棚の上に置く。", "にもつをたなのうえにおく。", "Place the package onto the shelf."],
  ["位", "イ / くらい", "i / kurai", "rank, grade, about", "順位 (jun'i - ranking)", "大会で第一位を獲得する。", "たいかいでだいいちいをつくとくする。", "Achieve first place in the tournament."],
  ["副", "フク", "fuku", "vice-, assistant, copy", "副詞 (fukushi - adverb)", "日本語の副詞の使い方を覚える。", "にほんごのふくしのつかいかたをおぼえる。", "Learn the usage of Japanese adverbs."],
  ["授", "ジュ / さず・ける", "ju / sazu-keru", "impart, instruct, award", "授業 (jugyou - lesson)", "大学で専門的な講義を授与される。", "だいがくでせんもんてきなこうぎをじゅよされる。", "Be taught specialized lectures at university."],
  ["配", "ハイ / くば・る", "hai / kuba-ru", "distribute, spouse", "心配 (shinpai - worry)", "プリントをクラス全員に配る。", "ぷりんとをくらすぜんいんにくばる。", "Distribute handouts to the whole class."],
  ["達", "タツ / たち", "tatsu / tachi", "accomplished, reach, plural", "発達 (hattatsu - development)", "文明が高度に発達する。", "ぶんめいがこうどにはったつする。", "Civilization develops to a high degree."],
  ["届", "カイ / とど・く", "kai / todo-ku", "deliver, reach, report", "届け出 (todokede - notification)", "大切な手紙が無事に届いた。", "たいせつなてがみがぶじにとどいた。", "The important letter safely arrived."],
  ["宅", "タク", "taku", "home, house, residence", "住宅 (juutaku - housing)", "静かな住宅街に暮らす。", "しずかなじゅうたくがいにくらす。", "Live in a quiet residential district."],
  ["宿", "シュク / やど", "shuku / yado", "inn, lodge, dwell", "宿題 (shukudai - homework)", "毎日の宿題をしっかり終わらせる。", "まいにちのしゅくだいをしっかりおわらせる。", "Firmly finish daily homework."],
  ["泊", "ハク / と・まる", "haku / to-maru", "overnight stay", "外泊 (gaihaku - staying overnight away)", "京都の旅館に二泊する。", "きょうとのりょかんににはくする。", "Stay two nights at a Kyoto inn."],
  ["乗", "ジョウ / の・る", "jou / no-ru", "ride, board, multiply", "乗車 (jousha - boarding)", "朝の通勤電車に乗る。", "あさのつうきんでんしゃにのる。", "Ride the morning commuter train."],
  ["降", "コウ / お・りる、ふ・る", "kou / o-riru, fu-ru", "descend, precipitate, fall", "降雪 (kousetsu - snowfall)", "静かに雪が降り積もる。", "しずかにゆきがふりつもる。", "Snow silently falls and accumulates."],
  ["呼", "コ / よ・ぶ", "ko / yo-bu", "call, invite, breathe", "点呼 (tenko - roll call)", "大きな声で名前を呼ぶ。", "おおきなこえでなまえをよぶ。", "Call out the name with a loud voice."],
  ["吸", "キュウ / す・う", "kyuu / su-u", "suck, inhale", "吸収 (kyuushuu - absorption)", "知識をスポンジのように吸収する。", "ちしきをすぽんじのようにきゅうしゅうする。", "Absorb knowledge like a sponge."],
  ["息", "ソク / いき", "soku / iki", "breath, son, interest", "休息 (kyuusoku - rest)", "深呼吸をして心を落ち着かせる。", "しんこきゅうをしてこころをおちつかせる。", "Take a deep breath and calm the mind."],
  ["忘", "ボウ / わす・れる", "bou / wasu-reru", "forget", "忘年会 (bounenkai - year-end party)", "恩師への感謝を忘れない。", "おんしへのかんしゃをわすれない。", "Never forget gratitude to one's mentor."],
  ["忙", "ボウ / いそが・しい", "bou / isoga-shii", "busy, hurried", "繁忙 (hanbou - busy season)", "年度末で仕事がとても忙しい。", "ねんどまつでしごとがとてもいそがしい。", "Work is very busy at fiscal year end."],
  ["恐", "キョウ / おそ・れる", "kyou / oso-reru", "fear, dread, awe", "恐縮 (kyoushuku - humble apologies)", "失敗を恐れずに挑戦し続ける。", "しっぱいをおそれずにてちょうせんしつづける。", "Keep challenging without fearing failure."],
  ["怖", "フ / こわ・い", "fu / kowa-i", "scary, dreadful", "恐怖 (kyoufu - fear)", "暗い夜道を歩くのは少し怖い。", "くらいよみちをあるくのはすこしこわい。", "Walking dark night roads is a bit scary."],
  ["怒", "ド / おこ・る", "do / oko-ru", "angry, be indignant", "怒気 (doki - anger)", "理由もなく怒ってはいけない。", "りゆうもなくおこってはいけない。", "One should not get angry without reason."],
  ["悲", "ヒ / かな・しい", "hi / kana-shii", "sad, sorrow, grieve", "悲劇 (higeki - tragedy)", "悲しいニュースに胸を痛める。", "かなしいにゅーすにむねをいためる。", "Pained at heart by the sad news."],
  ["喜", "キ / よろこ・ぶ", "ki / yoroko-bu", "rejoice, take pleasure in", "喜劇 (kigeki - comedy)", "友達の成功を心から喜ぶ。", "ともだちのせいこうをこころからよろこぶ。", "Genuinely rejoice in a friend's success."],
  ["笑", "ショウ / わら・う", "shou / wara-u", "laugh, smile", "爆笑 (bakushou - roar of laughter)", "楽しい冗談を聞いて笑う。", "たのしいじょうだんをきいてわらう。", "Laugh upon hearing a fun joke."],
  ["泣", "キュウ / な・く", "kyuu / na-ku", "cry, weep", "感泣 (kankyuu - crying with emotion)", "映画のラストシーンで思わず泣く。", "えいがのらすとしーんでおもわずなく。", "Involuntarily cry at the movie's last scene."],
  ["苦", "ク / くる・しい、にが・い", "ku / kuru-shii, niga-i", "suffering, bitter, hard", "苦心 (kushin - pains, effort)", "苦しい練習を乗り越えて優勝した。", "くるしいれんしゅうをのりこえてゆうしょうした。", "Overcame arduous training and won the championship."],
  ["痛", "ツウ / いた・い", "tsuu / ita-i", "pain, ache, hurt", "痛感 (tsuukan - feeling keenly)", "健康の大切さを痛感する。", "けんこうのたいせつさをつうかんする。", "Keenly feel the importance of health."],
  ["熱", "ネツ / あつ・い", "netsu / atsu-i", "heat, temperature, fever", "熱心 (nesshin - enthusiastic)", "熱心に日本語の勉強に打ち込む。", "ねっしんににほんごのべんきょうにうちこむ。", "Enthusiastically devote oneself to studying Japanese."],
  ["冷", "レイ / つめ・たい", "rei / tsume-tai", "cool, cold, chill", "冷蔵 (reizou - refrigeration)", "冷静に物事を判断する。", "れいせいにものごとをはんだんする。", "Judge matters calmly."],
  ["温", "オン / あたた・かい", "on / atata-kai", "warm", "温泉 (onsen - hot spring)", "温かい温泉に入ってリラックスする。", "あたたかいおんせんにはいってりらっくすする。", "Enter a warm hot spring and relax."],
  ["暖", "ダン / あたた・かい", "dan / atata-kai", "warmth", "暖房 (danbou - heating)", "春の暖かい日差しが心地よい。", "はるのあたたかいひざしがここちよい。", "The warm spring sunshine feels pleasant."],
  ["涼", "リョウ / すず・しい", "ryou / suzu-shii", "refreshing, cool", "夕涼み (yuusuzumi - cooling in evening)", "夕暮れの涼しい風を楽しむ。", "ゆうぐれのすずしいかぜをたのしむ。", "Enjoy the cool evening breeze."],
  ["甘", "カン / あま・い", "kan / ama-i", "sweet, pamper", "甘酒 (amazake - sweet sake)", "甘い果物を美味しくいただく。", "あまいくものをおいしくいただく。", "Deliciously enjoy sweet fruit."],
  ["辛", "シン / から・い", "shin / kara-i", "spicy, hot, painful", "辛口 (karakuchi - dry taste, biting)", "辛いスパイスの効いたカレーを食べる。", "からいすぱいすのきいたかれーをたべる。", "Eat curry seasoned with spicy seasonings."],
  ["塩", "エン / しお", "en / shio", "salt", "塩分 (enbun - salt content)", "塩分を控えめにした健康的な料理。", "えんぶんをひかえめにしたけんこうてきなりょうり。", "Healthy dishes with restrained salt content."],
  ["油", "ユ / あぶら", "yu / abura", "oil, fat", "油断 (yudan - carelessness)", "油断せずに最後まで集中する。", "ゆだんせずにさいごまでしゅうちゅうする。", "Stay focused without letting down one's guard until the end."],
  ["酒", "シュ / さけ", "shu / sake", "alcoholic drink, sake", "酒屋 (sakaya - liquor store)", "地元の銘酒を味わう。", "じもとのめいしゅをあじわう。", "Savor renowned local sake."],
  ["茶", "チャ、サ", "cha, sa", "tea", "喫茶 (kissa - tearoom)", "静かな喫茶店で本を読む。", "しずかなきっさてんでほんをよむ。", "Read a book at a quiet cafe."],
  ["米", "ベイ、マイ / こめ", "bei, mai / kome", "rice, USA, meter", "米国 (beikoku - USA)", "美味しいお米を丁寧に炊く。", "おいしいおこめにていねいにたく。", "Cook delicious rice carefully."],
  ["肉", "ニク", "niku", "meat, flesh", "筋肉 (kinniku - muscle)", "筋力トレーニングで筋肉を鍛える。", "きんりょくとれーにんぐできんにくをきたえる。", "Train muscles through strength training."],
  ["魚", "ギョ / さかな", "gyo / sakana", "fish", "金魚 (kingyo - goldfish)", "水族館で色とりどりの魚を見る。", "すいぞくかんでいろとりどりのさかなをみる。", "Look at colorful fish at the aquarium."],
  ["鳥", "チョウ / とり", "chou / tori", "bird, chicken", "白鳥 (hakuchou - swan)", "湖で優雅に泳ぐ白鳥を眺める。", "みずうみでゆうがにおよぐはくちょうをながめる。", "Gaze at swans swimming elegantly on the lake."],
  ["犬", "ケン / いぬ", "ken / inu", "dog", "番犬 (banken - watchdog)", "賢い犬が家を守っている。", "かしこいいぬがいえをまもっている。", "A clever dog protects the house."],
  ["虫", "チュウ / むし", "chuu / mushi", "insect, bug, temper", "害虫 (gaichuu - harmful insect)", "秋の夜に虫の音を聴く。", "あきのよるにむしのねをきく。", "Listen to the sounds of insects in autumn nights."],
  ["草", "ソウ / くさ", "sou / kusa", "grass, weeds, herbs", "薬草 (yakusou - medicinal herb)", "庭の草むしりをして整える。", "にわのくさむしりをしてととのえる。", "Weed the garden and tidy it up."],
  ["林", "リン / はやし", "rin / hayashi", "grove, forest", "竹林 (chikurin - bamboo grove)", "静かな竹林の道を散策する。", "しずかなちくりんのみちをさんさくする。", "Stroll through a quiet bamboo grove path."],
  ["森", "シン / もり", "shin / mori", "forest, woods", "森林浴 (shinrin'yoku - forest bathing)", "豊かな森で森林浴を楽しむ。", "ゆたかなもりでしんりんよくをたのしむ。", "Enjoy forest bathing in a rich forest."],
  ["池", "チ / いけ", "chi / ike", "pond, reservoir", "溜池 (tameike - reservoir)", "庭園の池に睡蓮が咲いている。", "ていえんのいけにすいれんがさいている。", "Water lilies bloom in the garden pond."],
  ["海", "カイ / うみ", "kai / umi", "sea, ocean", "海水 (kaisui - seawater)", "青く澄んだ海を船で渡る。", "あおくすんだうみをふねでわたる。", "Cross the clear blue sea by boat."],
  ["島", "トウ / しま", "tou / shima", "island", "無人島 (mujintou - uninhabited island)", "美しい離島を船で巡る。", "うつくしいりとうをふねでめぐる。", "Tour beautiful remote islands by boat."],
  ["岸", "ガン / きし", "gan / kishi", "beach, coast, bank", "湾岸 (wangan - gulf coast)", "夕暮れの海岸を静かに散歩する。", "ゆうぐれのかいがんをしずかにさんぽする。", "Quietly stroll the seashore at twilight."],
  ["岩", "ガン / いわ", "gan / iwa", "boulder, rock, cliff", "岩場 (iwaba - rocky area)", "険しい岩山を登る。", "けわしいいわやまをのぼる。", "Climb a steep rocky mountain."],
  ["港", "コウ / みなと", "kou / minato", "harbor, port", "港町 (minatomachi - port town)", "情緒ある港町の風景を楽しむ。", "じょうちょあるみなとまちのふうけいをたのしむ。", "Enjoy the atmosphere of the port town landscape."],
  ["練", "レン / ね・る", "ren / ne-ru", "practice, drill, polish", "練習 (renshuu - practice)", "毎日熱心に日本語の会話を練習する。", "まいにちねっしんににほんごのかいわをれんしゅうする。", "Practice Japanese conversation eagerly every day."],
  ["習", "シュウ / なら・う", "shuu / nara-u", "learn, custom", "復習 (fukushuu - review)", "授業の後に必ず復習を行う。", "じゅぎょうのあとにかならずふくしゅうをおこなう。", "Always conduct review after class."],
  ["勉", "ベン / つと・める", "ben / tsuto-meru", "exertion, diligence", "勉強 (benkyou - study)", "将来の夢のために勉学に励む。", "しょうらいのゆめのためにべんがくにはげむ。", "Work hard in studies for future dreams."],
  ["強", "キョウ、ゴウ / つよ・い", "kyou, gou / tsuyo-i", "strong, robust", "強調 (kyouchou - emphasis)", "強い意志を持って目標を達成する。", "つよいいしをもってもくひょうをたっせいする。", "Achieve the goal with a strong will."],
  ["弱", "ジャク / よわ・い", "jaku / yowa-i", "weak, feeble", "軟弱 (nanjaku - weak-kneed)", "弱音を吐かずに前進する。", "よわねをはかずにぜんしんする。", "Advance forward without giving voice to weakness."],
  ["重", "ジュウ、チョウ / おも・い、かさ・なる", "juu, chou / omo-i, kasa-naru", "heavy, important, pile up", "貴重 (kichou - precious)", "貴重なアドバイスを大切にする。", "きちょうなあどばいすをたいせつにする。", "Value precious advice."],
  ["軽", "ケイ / かる・い", "kei / karu-i", "light, minor, nimble", "軽減 (keigen - reduction)", "負担を軽減する工夫をする。", "ふたんをけいげんするくふうをする。", "Devise ways to reduce burden."],
  ["短", "タン / みじか・い", "tan / mijika-i", "short, brief, defect", "短所 (tansho - defect, weak point)", "長所を伸ばし短所を補う。", "ちょうしょをのばしたんしょをおぎなう。", "Develop strengths and supplement weaknesses."],
  ["長", "チョウ / なが・い", "chou / naga-i", "long, leader, excel", "市長 (shichou - mayor)", "長い道のりを一歩ずつ歩く。", "ながいみちのりをいっぽずつあるく。", "Walk a long journey step by step."],
  ["広", "コウ / ひろ・い", "kou / hiro-i", "wide, broad, spacious", "広大 (koudai - vast)", "広大な草原を風が吹き抜ける。", "こうだいなそうげんをかぜがふきぬける。", "The wind blows across the vast grassland."],
  ["狭", "キョウ / せま・い", "kyou / sema-i", "narrow, contract", "狭義 (kyougi - narrow sense)", "狭い道でも安全に運転する。", "せまいみちでもあんぜんにうんてんする。", "Drive safely even on narrow streets."],
  ["深", "シン / ふか・い", "shin / fuka-i", "deep, heighten, intensify", "深海 (shinkai - deep sea)", "深い友情で結ばれた仲間。", "ふかいうじょうでむすばれたなかま。", "Companions bonded with deep friendship."],
  ["浅", "セン / あさ・い", "sen / asa-i", "shallow, superficial", "浅慮 (senryo - indiscretion)", "浅い川を渡って対岸へ行く。", "あさいかわをわたってたいがんへいく。", "Cross a shallow river to the other bank."],
  ["高", "コウ / たか・い", "kou / taka-i", "tall, high, expensive", "高度 (koudo - altitude, high-level)", "高い志を持って生きる。", "たかいこころざしをもっていきる。", "Live with high aspirations."],
  ["低", "テイ / ひく・い", "tei / hiku-i", "low, humble, decline", "低下 (teika - fall, decline)", "低い姿勢で安全を確保する。", "ひくいしせいであんぜんをかくほする。", "Ensure safety with a low posture."],
  ["早", "ソウ / はや・い", "sou / haya-i", "early, fast", "早朝 (souchou - early morning)", "早朝の清々しい空気を吸う。", "そうちょうのすがすがしいくうきをすう。", "Breathe the refreshing air of early morning."],
  ["遅", "チ / おそ・い、おく・れる", "chi / oso-i, oku-reru", "slow, late, lag", "遅刻 (chikoku - lateness)", "遅れを取り戻すために急ぐ。", "おくれをとりもどすためにいそぐ。", "Hurry to make up for lost time."],
  ["速", "ソク / はや・い", "soku / haya-i", "fast, speedy", "高速 (kousoku - high speed)", "高速道路を利用して移動する。", "こうそくどうろをりようしていどうする。", "Travel using the expressway."],
  ["遅", "チ / おく・れる", "chi / oku-reru", "late, delay", "遅延 (chien - delay)", "列車が遅延する。", "れっしゃがちえんする。", "The train is delayed."]
];

for (const row of n3Master) n3.add(...row);
n3.save('n3.json');

// ----------------------------------------------------
// N2 BUILDER
// ----------------------------------------------------
const n2 = makeBuilder('N2', 150);

const n2Master = [
  ["職", "ショク / そく", "shoku / soku", "post, employment, work", "職業 (shokugyou - occupation)", "専門的な知識を活かした職に就く。", "せんもんてきなちしきをいかしたしょくにつく。", "Get a job utilizing specialized knowledge."],
  ["容", "ヨウ / い・れる", "you / i-reru", "contain, form, looks", "内容 (naiyou - contents)", "書類の内容をしっかり把握する。", "しょるいのないようをしっかりはあくする。", "Firmly grasp the contents of the document."],
  ["演", "エン", "en", "performance, act, play", "演技 (engi - acting)", "舞台で見事な演技を披露する。", "ぶたいでみごとなえんぎをひろうする。", "Showcase superb acting on stage."],
  ["党", "トウ", "tou", "party, faction, clique", "政党 (seitou - political party)", "政党の基本政策を比較する。", "せいとうのきほんせいさくをひかくする。", "Compare basic policies of political parties."],
  ["規", "キ", "ki", "standard, measure", "規則 (kisoku - rule)", "安全基準の規則を遵守する。", "あんぜんきじゅんのきそくをじゅんしゅする。", "Comply with the regulations of safety standards."],
  ["得", "トク / え・る、う・る", "toku / e-ru, u-ru", "gain, get, profit", "納得 (nattoku - consent)", "貴重な経験と知見を得る。", "きちょうなけいけんとちけんをえる。", "Gain valuable experience and insights."],
  ["資", "シ", "shi", "assets, resources, capital", "資格 (shikaku - qualification)", "専門資格の取得に向けて猛勉強する。", "せんもんしかくのしゅとくにむけてもうべんきょうする。", "Study intensely towards acquiring specialized qualifications."],
  ["閣", "カク", "kaku", "tower, palace, cabinet", "内閣 (naikaku - cabinet)", "内閣の支持率が報道される。", "ないかくのしじりつがほうどうされる。", "The cabinet approval rating is reported."],
  ["官", "カン", "kan", "bureaucrat, the government", "官僚 (kanryou - bureaucrat)", "外交官として海外に赴任する。", "がいこうかんとしてかいがいにふにんする。", "Be posted overseas as a diplomat."],
  ["省", "ショウ、セイ / はぶ・く、かえり・みる", "shou, sei / habu-ku, kaeri-miru", "focus, government ministry, omit", "反省 (hansei - reflection)", "過去の失敗を真摯に反省する。", "かこのしっぱいにしんしにはんせいする。", "Sincerely reflect upon past mistakes."],
  ["責", "セキ / せ・める", "seki / se-meru", "blame, condemn, responsibility", "責任 (sekinin - responsibility)", "リーダーとしての責任を果たす。", "りーだーとしてのせきにんをはたす。", "Fulfill one's responsibility as a leader."],
  ["任", "ニン / まか・せる", "nin / maka-seru", "responsibility, duty, entrust", "任務 (ninmu - mission)", "重要な任務を任される。", "じゅうようなにんむをまかされる。", "Be entrusted with an important mission."],
  ["処", "ショ", "sho", "dispose, manage, deal with", "処理 (shori - processing)", "大量のデータを素早く処理する。", "たいりょうのでーたをすばやくしょりする。", "Quickly process large amounts of data."],
  ["貿", "ボウ", "bou", "trade, exchange", "貿易 (boueki - foreign trade)", "海外の企業と貿易を行う。", "かいがいのきぎょうとぼうえきをおこなう。", "Conduct trade with overseas enterprises."],
  ["防", "ボウ / ふせ・ぐ", "bou / fuse-gu", "ward off, defend, prevent", "防止 (boushi - prevention)", "事故の再発を未然に防ぐ。", "じこのさいはつを未然にふせぐ。", "Prevent recurrence of accidents beforehand."],
  ["補", "ホ / おぎな・う", "ho / ogina-u", "supplement, supply, assist", "補充 (hojuu - replenishment)", "不足している栄養を補う。", "ふそくしているえいようをおぎなう。", "Supplement lacking nutritional needs."],
  ["批", "ヒ", "hi", "criticism, strike", "批判 (hihan - criticism)", "建設的な批判を受け入れて改善する。", "けんせつてきなひはんをうけいれてかいぜんする。", "Accept constructive criticism to make improvements."],
  ["断", "ダン / た・つ、ことわ・る", "dan / ta-tsu, kotowa-ru", "sever, refuse, decision", "判断 (handan - judgment)", "冷静な判断を下す。", "れいせいなはんだんをくだす。", "Make a calm judgment."],
  ["導", "ドウ / みちび・く", "dou / michibi-ku", "guidance, leading, conduct", "指導 (shidou - leadership, guidance)", "初心者を親切に導く。", "しょしんしゃをしんせつにみちびく。", "Kindly guide beginners."],
  ["認", "ニン / みと・める", "nin / mito-meru", "acknowledge, witness, recognize", "確認 (kakunin - confirmation)", "努力の成果を正当に認める。", "どりょくのせいかをせいとうにみとめる。", "Rightly recognize the fruits of effort."],
  ["疑", "ギ / うたが・う", "gi / utaga-u", "doubt, distrust, be suspicious", "疑問 (gimon - question, doubt)", "真実について疑いを持つ。", "しんじつについてうたがいをもつ。", "Harbor doubts about the truth."],
  ["講", "コウ", "kou", "lecture, study", "講義 (kougi - lecture)", "大学で専門講義を熱心に聴く。", "だいがくでせんもんこうぎをねっしんにきく。", "Enthusiastically listen to specialized lectures at university."],
  ["義", "ギ", "gi", "justice, honor, loyalty", "正義 (seigi - justice)", "社会の正義を守るために行動する。", "しゃかいのせいぎをまもるためによりこうどうする。", "Act to protect justice in society."],
  ["論", "ロン", "ron", "argument, discourse, theory", "理論 (riron - theory)", "論理的な思考力を鍛える。", "ろんりてきなしこうりょくをきたえる。", "Train logical thinking ability."],
  ["討", "トウ / う・つ", "tou / u-tsu", "chastise, attack, discuss", "検討 (kentou - examination)", "改善案をチームで検討する。", "かいぜんあんをちーむでけんとうする。", "Examine improvement proposals in the team."],
  ["識", "シキ", "shiki", "discriminating, know, write", "知識 (chishiki - knowledge)", "豊かな専門知識を蓄える。", "ゆたかなせんもんちしきをたくわえる。", "Accumulate rich specialized knowledge."],
  ["境", "キョウ、ケイ / さかい", "kyou, kei / sakai", "boundary, border, region", "環境 (kankyou - environment)", "自然環境を後世に残す。", "しぜんかんきょうをこうせいにのこす。", "Leave natural environment for future generations."],
  ["態", "タイ / わざ・と", "tai / waza-to", "attitude, condition, appearance", "態度 (taido - attitude)", "誠実な態度で人と接する。", "せいじつなたいどでひととせっする。", "Interact with people with a sincere attitude."],
  ["勢", "セイ / いきお・い", "sei / ikio-i", "forces, energy, vigor", "姿勢 (shisei - posture, attitude)", "前向きな姿勢で困難に立ち向かう。", "まえむきなしせいでこんなんにたちむかう。", "Confront difficulties with a forward-looking attitude."],
  ["総", "ソウ / す・べて", "sou / su-bete", "general, whole, all", "総合 (sougou - synthesis)", "総合的な判断が求められる。", "そうごうてきなはんだんがもとめられる。", "Comprehensive judgment is required."],
  ["設", "セツ / もう・ける", "setsu / mou-keru", "establishment, provision", "施設 (shisetsu - facility)", "地域に新しい公共施設を建設する。", "ちいきにあたらしいこうきょうしせつをけんせつする。", "Construct new public facilities in the area."],
  ["案", "アン", "an", "plan, suggestion, draft", "提案 (teian - proposal)", "業務効率化のための妙案を出す。", "ぎょうむこうりつかのためのみょうあんをだす。", "Put forward an ingenious proposal for efficiency."],
  ["提", "テイ / さ・げる", "tei / sa-geru", "propose, take in hand", "提出 (teishutsu - submission)", "レポートを期限までに提出する。", "れぽーとをきげんまでにていしゅつする。", "Submit the report by the deadline."],
  ["供", "キョウ、ク / とも、そな・える", "kyou, ku / tomo, sona-eru", "submit, offer, accompany", "提供 (teikyou - provision)", "高品質なサービスを提供する。", "こうひんしつなさーびすをていきょうする。", "Provide high quality services."],
  ["標", "ヒョウ / しるし", "hyou / shirushi", "signpost, mark, target", "目標 (mokuhyou - goal)", "目標に向かって日々前進する。", "もくひょうにむかってひびぜんしんする。", "Move forward daily towards goals."],
  ["創", "ソウ / つく・る", "sou / tsuku-ru", "create, originate, establish", "創造 (souzou - creation)", "独創的なアイデアを形にする。", "どくそうてきなあいであをかたちにする。", "Turn creative ideas into tangible form."],
  ["訪", "ホウ / おとず・れる", "hou / otozu-reru", "visit, call on", "訪問 (houmon - visit)", "海外の提携先を訪問する。", "かいがいのていけいさきをほうもんする。", "Visit overseas partner organizations."],
  ["景", "ケイ", "kei", "scenery, view", "景色 (keshiki - scenery)", "展望台から素晴らしい夜景を眺める。", "てんぼうだいからすばらしいやけいをながめる。", "Gaze upon a splendid night view from the observatory."],
  ["況", "キョウ / まし・て", "kyou / mashi-te", "condition, situation", "状況 (joukyou - situation)", "現在の状況を冷静に分析する。", "げんざいのじょうきょうをれいせいにぶんせきする。", "Analyze the current situation calmly."],
  ["構", "コウ / かま・える", "kou / kama-eru", "structure, construct, posture", "構造 (kouzou - structure)", "建物の耐震構造を強化する。", "たてもののたいしんこうぞうをきょうかする。", "Reinforce earthquake-resistant structure of the building."],
  ["造", "ゾウ / つく・る", "zou / tsuku-ru", "create, make, build", "製造 (seizou - manufacturing)", "日本のものづくり精神を尊重する。", "にほんのものづくりせいしんをそんちょうする。", "Respect the spirit of Japanese craftsmanship."],
  ["模", "モ、ボ", "mo, bo", "imitation, copy, mock", "規模 (kibo - scale)", "大規模な国際会議が開催される。", "だいきぼなこくさいかいぎがかいさいされる。", "A large-scale international conference is held."],
  ["範", "ハン", "han", "pattern, example, model", "模範 (mohan - model, exemplar)", "模範的な行動を心がける。", "もはんてきなこうどうをこころがける。", "Keep exemplary behavior in mind."],
  ["域", "イキ", "iki", "range, region, limits", "地域 (chiiki - region, local)", "地域社会に貢献する活動を行う。", "ちいきしゃかいにこうけんするかつどうをおこなう。", "Engage in activities contributing to local community."],
  ["拡", "カク / ひろ・がる", "kaku / hiro-garu", "broaden, extend, expand", "拡大 (kakudai - expansion)", "事業の規模を海外へ拡大する。", "じぎょうのきぼをかいがいへかくだいする。", "Expand business operations abroad."],
  ["縮", "シュク / ちぢ・む", "shuku / chiji-mu", "shrink, contract, reduce", "短縮 (tanshuku - shortening)", "移動時間を大幅に短縮する。", "いどうじかんをおおはばにたんしゅくする。", "Significantly shorten transit time."],
  ["優", "ユウ / やさ・しい、すぐ・れる", "yuu / yasa-shii, sugu-reru", "superior, gentle, excel", "優秀 (yuushuu - excellent)", "人に優しく接する温かい心。", "ひとにやさしくせっするあたたかいこころ。", "A warm heart that treats others gently."],
  ["秀", "シュウ / ひい・でる", "shuu / hii-deru", "surpass, excel, beauty", "優秀 (yuushuu - excellence)", "秀でた才能を磨く。", "ひいでたさいのうをみがく。", "Polish one's outstanding talent."],
  ["劣", "レツ / おと・る", "retsu / oto-ru", "inferiority, be inferior", "劣等感 (rettoukan - inferiority complex)", "他人に劣らぬ熱意を持つ。", "たにんにおとらぬねついをもつ。", "Have enthusiasm second to none."],
  ["充", "ジュウ / あ・てる", "juu / a-teru", "allot, fill", "充実 (juujitsu - fulfillment)", "充実した毎日を過ごす。", "じゅうじつしたまいにちをすごす。", "Spend every day in fulfillment."],
  ["乏", "ボウ / とぼ・しい", "bou / tobo-shii", "destitution, scarce, lack", "貧乏 (binbou - poor)", "経験が乏しい時期を乗り越える。", "けいけんがとぼしいじきをのりこえる。", "Overcome the period of scarce experience."],
  ["富", "フ、フウ / と・む、とみ", "fu, fuu / to-mu, tomi", "wealth, enrich, abundant", "豊富 (houfu - abundant)", "豊富な知識を持つ専門家。", "ほうふなちしきをもつせんもんか。", "An expert with abundant knowledge."],
  ["貧", "ヒン、ビン / まず・しい", "hin, bin / mazu-shii", "poverty, poor", "貧困 (hinkon - poverty)", "世界の貧困問題を考える。", "せかいのひんこんもんだいをかんがえる。", "Contemplate the world's poverty problems."],
  ["純", "ジュン", "jun", "genuine, purity, innocent", "純粋 (junsui - pure)", "純粋な心で学問に向き合う。", "じゅんすいなこころでがくもんにむきあう。", "Approach academia with a pure heart."],
  ["粋", "スイ / いき", "sui / iki", "chic, style, purity", "純粋 (junsui - genuine)", "日本の粋な文化を嗜む。", "にほんのいきなぶんかをたしなむ。", "Enjoy stylish and chic Japanese culture."],
  ["粗", "ソ / あら・い", "so / ara-i", "coarse, rough, crude", "粗大 (sodai - bulky)", "粗末に扱わず大切に使う。", "そまつにあつかわずたいせつにつかう。", "Use carefully without treating crudely."],
  ["精", "セイ、ショウ", "sei, shou", "refined, ghost, fairy, energy", "精神 (seishin - spirit, mind)", "不屈の精神で努力を重ねる。", "ふくつのせいしんでどりょくをかさねる。", "Stack up effort with an indomitable spirit."],
  ["神", "シン、ジン / かみ", "shin, jin / kami", "gods, mind, soul", "神社 (jinja - Shinto shrine)", "初詣で神社に参拝する。", "はつもうででじんじゃにさんぱいする。", "Worship at a shrine during New Year's visit."],
  ["仏", "ブツ、フツ / ほとけ", "butsu, futsu / hotoke", "Buddha, France", "仏教 (bukkyou - Buddhism)", "仏教美術の美しさに心打たれる。", "ぶっきょうびじゅつのうつくしさにこころうたれる。", "Struck by the beauty of Buddhist art."],
  ["宗", "シュウ、ソウ", "shuu, sou", "religion, sect, origin", "宗教 (shuukyou - religion)", "各国の宗教と文化の違いを理解する。", "かっこくのしゅうきょうとぶんかのちがいをりかいする。", "Understand differences in religions and cultures across nations."],
  ["儀", "ギ", "gi", "ceremony, rule, affair", "礼儀 (reigi - etiquette)", "礼儀正しく挨拶を交わす。", "れいぎただしくあいさつをかわす。", "Exchange greetings politely and well-mannered."],
  ["式", "シキ", "shiki", "style, ceremony, formula", "卒業式 (sotsugyoushiki - graduation ceremony)", "厳かな雰囲気の中で式典が行われる。", "おごそかなふんいきのなかでしきてんがおこなわれる。", "Ceremony is conducted within a solemn atmosphere."],
  ["祭", "サイ / まつ・る、まつ・り", "sai / matsu-ru, matsu-ri", "festival, ritual, celebrate", "祭り (matsuri - festival)", "伝統の夏祭りに参加して楽しむ。", "でんとうのなつまつりにさんかしてたのしむ。", "Participate in and enjoy the traditional summer festival."],
  ["祝", "シュク、シュウ / いわ・う", "shuku, shuu / iwa-u", "celebrate, congratulate", "祝福 (shukufuku - blessing)", "友人の結婚を心から祝う。", "ゆうじんのけっこんをこころからいわう。", "Heartily celebrate a friend's wedding."],
  ["福", "フク", "fuku", "blessing, fortune, luck", "幸福 (koufuku - happiness)", "日々の小さな幸福を実感する。", "ひびのちいさなこうふくをじっかんする。", "Feel small daily happinesses."],
  ["幸", "コウ / さいわ・い、しあわ・せ", "kou / saiwa-i, shiawa-se", "happiness, blessing", "幸運 (kouun - good fortune)", "素晴らしい仲間と出会えて幸せだ。", "すばらしいなかまとであえてしあわせだ。", "Happy to have met wonderful companions."],
  ["災", "サイ / わざわ・い", "sai / wazawa-i", "disaster, calamity", "防災 (bousai - disaster prevention)", "防災訓練に真剣に参加する。", "ぼうさいくんれんにしんけんにさんかする。", "Earnestly take part in disaster prevention drills."],
  ["害", "ガイ", "gai", "harm, damage", "被害 (higai - damage)", "台風による被害を最小限に抑える。", "たいふうによるひがいをさいしょうげんにおさえる。", "Suppress damage by typhoons to a minimum."],
  ["救", "キュウ / すく・う", "kyuu / suku-u", "rescue, save, help", "救済 (kyuusai - relief)", "困難な状況にある人々を救う。", "こんなんなじょうきょうにあるひとびとをすくう。", "Save people in difficult situations."],
  ["助", "ジョ / たす・ける、たす・かる", "jo / tasu-keru, tasu-karu", "help, rescue, assist", "助手 (joshu - assistant)", "お互いに助け合って課題を解決する。", "おたがいにたすけあってかだいをかいけつする。", "Solve issues by helping one another."],
  ["援", "エン", "en", "aid, help, assist", "応援 (ouen - cheering, support)", "夢に向かって頑張る友達を応援する。", "ゆめにむかってがんばるともだちをおうえんする。", "Cheer on a friend working hard toward dreams."]
];

for (const row of n2Master) n2.add(...row);
n2.save('n2.json');

// ----------------------------------------------------
// N1 BUILDER
// ----------------------------------------------------
const n1 = makeBuilder('N1', 150);

const n1Master = [
  ["概", "ガイ / おおむ・ね", "gai / oomu-ne", "outline, condition, general", "概念 (gainen - concept)", "新しい哲学的な概念を考察する。", "あたらしいてつがくてきながいねんをこうさつする。", "Examine a new philosophical concept."],
  ["妥", "ダ", "da", "gentle, peace, appropriate", "妥当 (datou - valid, proper)", "その意見には妥当性がある。", "そのいけんにはだとうせいがある。", "There is validity to that opinion."],
  ["矛", "ム、ボウ / ほこ", "mu, bou / hoko", "halberd, spear", "矛盾 (mujun - contradiction)", "言動の矛盾を指摘される。", "げんどうのむじゅんをしてきされる。", "Have contradictions in words and deeds pointed out."],
  ["盾", "ジュン / たて", "jun / tate", "shield, escutcheon", "矛盾 (mujun - inconsistency)", "矛と盾の故事から学ぶ。", "ほことたてのこじからまなぶ。", "Learn from the historical fable of spear and shield."],
  ["欺", "ギ / あざむ・く", "gi / azamu-ku", "deceit, cheat, delude", "欺瞞 (giman - deception)", "敵の目を欺いて逃走する。", "てきのめをあざむいてとうそうする。", "Deceive the enemy's eyes and escape."],
  ["瞞", "マン", "man", "deceive, delude", "欺瞞 (giman - deception)", "欺瞞に満ちた説明に抗議する。", "ぎまんにみちたせつめいにこうぎする。", "Protest explanations filled with deceit."],
  ["懸", "ケン、ケ / か・ける", "ken, ke / ka-keru", "suspend, hang, depend", "懸念 (kenen - concern, anxiety)", "景気の後退が深く懸念される。", "けいきのこうたいがふかくけねんされる。", "Economic decline is deeply feared."],
  ["念", "ネン", "nen", "wish, sense, idea, thought", "記念 (kinen - commemoration)", "感謝の念を常に心に抱く。", "かんしゃのねんをつねにこころにいだく。", "Always hold feelings of gratitude in one's heart."],
  ["脆", "ゼイ / もろ・い", "zei / moro-i", "brittle, fragile, frail", "脆弱 (zeijaku - vulnerable, frail)", "セキュリティの脆弱性を修正する。", "せきゅりてぃのぜいじゃくせいをしゅうせいする。", "Fix the security vulnerability."],
  ["顕", "ケン / あきらか", "ken / akiraka", "manifest, prominent, clear", "顕著 (kencho - remarkable, striking)", "温暖化の影響が顕著に現れる。", "おんだんかのえいきょうがけんちょにあらわれる。", "The impact of global warming appears remarkably."],
  ["著", "チョ、チャク / あらわ・す、いちじる・しい", "cho, chaku / arawa-su, ichijiru-shii", "renowned, publish, write", "著名 (chomei - famous, prominent)", "著名な学者による論文を読む。", "ちょめいながくしゃによるろんぶんをよむ。", "Read a paper by a prominent scholar."],
  ["索", "サク", "saku", "cord, rope, search", "検索 (kensaku - search)", "情報をインターネットで検索する。", "じょうほうをいんたーねっとでけんさくする。", "Search for information on the internet."],
  ["瓦", "ガ / かわら", "ga / かわら", "tile, gram", "瓦解 (gakai - collapse)", "古い家の屋根瓦を修復する。", "ふるいいえのやねがわらをしゅうふくする。", "Restore the roof tiles of an old house."],
  ["乖", "カイ / そむ・く", "kai / somu-ku", "diverge, estrange, alienate", "乖離 (kairi - alienation, divergence)", "理想と現実の乖離に悩む。", "りそうとげんじつのかいりになやむ。", "Worry over the divergence between ideal and reality."],
  ["離", "リ / はな・れる、はな・す", "ri / hana-reru, hana-su", "detach, separate, leave", "分離 (bunri - separation)", "故郷を遠く離れて暮らす。", "こきょうをとおくはなれてくらす。", "Live far separated from one's hometown."],
  ["卓", "タク", "taku", "eminent, table, desk", "卓越 (takuetsu - excellence)", "卓越した技術を持つ職人。", "たくえつしたぎじゅつをもつしょくにん。", "An artisan possessing superior craftsmanship."],
  ["越", "エツ / こ・える", "etsu / ko-eru", "surpass, cross over, exceed", "超越 (chouetsu - transcendence)", "国境を越えて人々が助け合う。", "こっきょうをこえてひとびとがたすけあう。", "People help one another crossing national borders."],
  ["掌", "ショウ / てのひら", "shou / tenohira", "manipulate, palm of hand", "掌握 (shouaku - seize control)", "全権をその手中に掌握する。", "ぜんけんをそのしゅちゅうにしょうあくする。", "Seize all authority into one's grasp."],
  ["握", "アク / にぎ・る", "aku / nigi-ru", "grip, hold, wield", "握手 (akushu - handshake)", "しっかりと手を握り締める。", "しっかりとてをにぎりしめる。", "Firmly grasp hands."],
  ["看", "カン / み・る", "kan / mi-ru", "watch over, see", "看過 (kanka - overlook)", "不正行為を決して看過しない。", "ふせいこういをけっしてかんかしない。", "Never overlook illicit behavior."],
  ["過", "カ / す・ぎる、あやま・ち", "ka / su-giru, ayama-chi", "overdo, exceed, mistake", "過去 (kako - past)", "過去の経験を未来に活かす。", "かこのけいけんをみらいにいかす。", "Apply past experiences to the future."],
  ["糾", "キュウ", "kyuu", "twist, ask, censure", "糾弾 (kyuudan - denunciation)", "不正を犯した者を厳しく糾弾する。", "ふせいをやかしたものをきびしくきゅうだんする。", "Strictly denounce those who committed malpractice."],
  ["弾", "ダン / ひ・く、たま", "dan / hi-ku, tama", "bullet, bounce, play string", "弾劾 (dangai - impeachment)", "ピアノの鍵盤を軽快に弾く。", "ぴあののけんばんをけいかいにひく。", "Lightly play the keys of the piano."],
  ["克", "コク / か・つ", "koku / ka-tsu", "overcome, skillfully", "克服 (kokufuku - overcoming)", "病気を強い意志で克服する。", "びょうきをつよいいしでこくふくする。", "Overcome illness with a strong will."],
  ["拘", "コウ / かにかわ・る", "kou / kani-kawa-ru", "arrest, stick to, detain", "拘束 (kousoku - restriction)", "些細な形式に拘泥しない。", "ささいなけいしきにこうでいしない。", "Do not adhere obstinately to trivial formalities."],
  ["唆", "サ / そそのか・す", "sa / sosonoka-su", "instigate, tempt", "示唆 (shisa - implication)", "今後の指針を示唆する報告。", "こんごのししんをしさするほうこく。", "A report suggesting future guidelines."],
  ["収", "シュウ / おさ・める", "shuu / osa-meru", "take in, obtain, harvest", "収斂 (shuuren - convergence)", "様々な議論が一つの結論に収斂する。", "さまざまなぎろんがひとつのけつろんにしゅうれんする。", "Various debates converge toward one conclusion."],
  ["斂", "レン / おさ・める", "ren / osa-meru", "gather, collect", "収斂 (shuuren - gathering, condensing)", "多様な視点を集約し収斂させる。", "たようなしてんをしゅうやくししゅうれんさせる。", "Integrate and converge diverse viewpoints."],
  ["是", "ゼ / これ", "ze / kore", "just so, right, correct", "是正 (zesei - correction)", "不合理な慣習を是正する。", "ふごうりなかんしゅうをぜせいする。", "Rectify irrational customs."],
  ["拙", "セツ / つたな・い", "setsu / tsutana-i", "clumsy, unskillful, humble", "拙速 (sessoku - quick though rough)", "巧遅より拙速を尊ぶ場合もある。", "こうちよりせっそくをとうとぶばあいもある。", "There are cases where prompt action is valued over slow perfection."],
  ["遡", "ソ / さかのぼ・る", "so / sakanobo-ru", "go back, trace to source", "遡及 (sokyuu - retroactive)", "川の流れを上流へと遡る。", "かわのながれをじょうりゅうへとさかのぼる。", "Go up the river towards the upper stream."],
  ["及", "キュウ / およ・ぶ、およ・ぼす", "kyuu / oyo-bu, oyo-bosu", "reach out, exert, extend", "波及 (hakyuu - ripple effect)", "影響が社会全体に及ぶ。", "えいきょうがしゃかいぜんたいにおよぶ。", "The influence extends across society."],
  ["殺", "サツ、サイ / ころ・す", "satsu, sai / koro-su", "kill, diminish, offset", "相殺 (sousai - cancellation)", "損益を相殺して計算する。", "そんえきをそうさいしてけいさんする。", "Calculate after offsetting gains and losses."],
  ["阻", "ソ / はば・む", "so / haba-mu", "thwart, separate, deter", "阻害 (sogai - obstruction)", "健全な発展を阻害する要因を除く。", "けんぜんなはってんをそがいするよういんをのぞく。", "Eliminate factors that obstruct healthy development."],
  ["淘", "トウ / よな・げる", "tou / yona-geru", "select, wash out", "淘汰 (touta - weeding out)", "時代の変化で古い制度が淘汰される。", "じだいのへんかでふるいせいどがとうたされる。", "Old systems are weeded out by changing times."],
  ["汰", "タ", "ta", "luxury, wash out, select", "淘汰 (touta - selection)", "市場競争による自然淘汰。", "しじょうきょうそうによるしぜんとうた。", "Natural selection through market competition."],
  ["踏", "トウ / ふ・む", "tou / fu-mu", "step, trample, carry out", "踏襲 (toushuu - follow precedent)", "前人の輝かしい業績を踏襲する。", "ぜんじんのかがやかしいぎょうせきをとうしゅうする。", "Follow in the illustrious achievements of predecessors."],
  ["襲", "シュウ / おそ・う", "shuu / oso-u", "attack, advance, succeed to", "襲名 (shuumei - succession to a name)", "伝統ある芸名を堂々と襲名する。", "でんとうあるげいめいをどうどうとしゅうめいする。", "Dignifiedly succeed to a traditional stage name."],
  ["頓", "トン / とみ・に", "ton / tomi-ni", "suddenly, bow, pause", "頓挫 (tonza - sudden halt)", "資金不足で建設計画が頓挫した。", "しきんぶそくでけんせつけいかくがとんざした。", "The construction plan stalled due to lack of funds."],
  ["挫", "ザ / くじ・く、くじ・ける", "za / kuji-ku, kuji-keru", "sprain, crush, dampen", "挫折 (zasetsu - setback)", "挫折をバネにしてさらに成長する。", "ざせつをばねにしてさらにせいちょうする。", "Grow even further using setbacks as a springboard."],
  ["破", "ハ / やぶ・る", "ha / yabu-ru", "rend, rip, break", "破綻 (hatan - collapse)", "世界記録を堂々と打ち破る。", "せかいきろくをどうどうとうちやぶる。", "Gloriously break the world record."],
  ["綻", "タン / ほころ・びる", "tan / hokoro-biru", "rip, come undone, smile", "破綻 (hatan - bankruptcy)", "桜のつぼみが春に綻びる。", "さくらのつぼみがはるにほころびる。", "Cherry blossoms buds begin to open in spring."],
  ["肩", "ケン / かた", "ken / kata", "shoulder", "比肩 (hiken - standing shoulder to shoulder)", "荷物を肩にかついで運ぶ。", "にもつをかたにかついではこぶ。", "Carry the luggage shouldering it on one's back."],
  ["逼", "ヒツ / せま・る", "hitsu / sema-ru", "approach, urgent, pressed", "逼迫 (hippaku - stringency)", "医療供給の体制が逼迫する。", "いりょうきょうきゅうのたいせいがひっぱくする。", "The medical supply structure is severely strained."],
  ["迫", "ハク / せま・る", "haku / sema-ru", "urge, force, imminent", "切迫 (seppaku - tension)", "締切の日時が間近に迫る。", "しめきりのにちじがまぢかにせまる。", "The deadline approaches closely."],
  ["括", "カツ / くく・る", "katsu / kuku-ru", "fasten, tie, summarize", "総括 (soukatsu - summary)", "一年の研究成果を総括する。", "いちねんのけんきゅうせいかをそうかつする。", "Summarize the research results of the year."],
  ["完", "カン", "kan", "perfect, completion", "完全 (kanzen - perfection)", "すべての準備が完全に完了した。", "すべてのじゅんびがかんぜんにかんりょうした。", "All preparations have been completely finished."],
  ["萌", "ホウ / も・える", "hou / mo-eru", "sprout, bud, germ", "萌芽 (houga - germ, sprout)", "春の山に草木が一斉に萌え出ずる。", "はるのやまにくさきがいっせいにもえいずる。", "Trees and grass sprout all at once in the spring mountain."],
  ["芽", "ガ / め", "ga / me", "bud, sprout, spear", "発芽 (hatsuga - germination)", "小さな種から新しい芽が出る。", "ちいさなたねからあたらしいめがでる。", "New sprouts emerge from small seeds."],
  ["膨", "ボウ / ふく・らむ", "bou / fuku-ramu", "swell, get fat, expand", "膨張 (bouchou - expansion)", "宇宙は今も膨張を続けている。", "うちゅうはいまもぼうちょうをつづけている。", "The universe continues to expand even now."],
  ["張", "チョウ / は・る", "chou / ha-ru", "stretch, spread, strain", "主張 (shuchou - claim)", "テントを広場にしっかりと張る。", "てんとをひろばにしっかりとはる。", "Firmly pitch a tent in the plaza."],
  ["蔓", "マン / つる、はびこ・る", "man / tsuru, habiko-ru", "vine, spread, rampancy", "蔓延 (man'en - epidemic)", "蔦の蔓が壁を伝って伸びる。", "つたのつるがかべをつたってのびる。", "Ivy vines stretch along the wall."],
  ["延", "エン / の・びる、の・べる", "en / no-biru, no-beru", "prolong, extend, postpone", "延長 (enchou - extension)", "試合の時間が延長された。", "しあいのじかんがえんちょうされた。", "The match time was extended."],
  ["未", "ミ、ビ / いま・だ", "mi, bi / ima-da", "not yet, un-", "未来 (mirai - future)", "未曾有の困難に団結して立ち向かう。", "みぞうのこんなんにだんけつしてたちむかう。", "Confront unprecedented difficulties in solidarity."],
  ["曾", "ソウ、ゾウ / かつ・て", "sou, zou / katsu-te", "formerly, once, ever", "未曾有 (mizou - unexampled)", "未曾有の大記録を打ち立てる。", "みぞうのだいきろくをうちたてる。", "Establish an unprecedented grand record."],
  ["残", "ザン / のこ・る", "zan / noko-ru", "remainder, leftover", "残念 (zannen - regrettable)", "雪が山頂に白く残っている。", "ゆきがさんちょうにしろくのこっている。", "Snow remains white on the mountain peak."],
  ["抑", "ヨク / おさ・える", "yoku / osa-eru", "repress, push down", "抑制 (yokusei - inhibition)", "感情を高ぶらせず冷静に抑える。", "かんじょうをたかぶらせずれいせいにおさえる。", "Calmly restrain emotions without getting agitated."],
  ["累", "ルイ", "rui", "accumulate, involve", "累計 (ruikei - cumulative total)", "長年の累計実績が認められる。", "ながねんのるいけいじっせきがみとめられる。", "Cumulative track record over years is acknowledged."],
  ["露", "ロ、ロウ / つゆ", "ro, rou / tsuyu", "dew, exposed, open", "露呈 (rotei - exposure)", "草の葉に朝露が輝いている。", "くさのはにあさつゆがかがやいている。", "Morning dew shines on the leaves of grass."],
  ["呈", "テイ", "tei", "display, offer, present", "進呈 (shintei - presentation)", "記念品を参加者に進呈する。", "きねんひんをさんかしゃにしんていする。", "Present commemorative gifts to participants."],
  ["矮", "ワイ", "wai", "low, dwarf, short", "矮小 (waishou - diminutive, petty)", "重大な問題を矮小化してはならない。", "じゅうだいなもんだいをわいしょうかしてはならない。", "Critical problems must not be minimized."],
  ["慶", "ケイ / よろこ・び", "kei / yoroko-bi", "jubilation, rejoice, congratulate", "慶事 (keiji - auspicious event)", "心からのお慶びを申し上げます。", "こころからのおよろこびをもうしあげます。", "I offer my heartfelt congratulations."],
  ["蔑", "ベツ / さげす・む", "betsu / sagesu-mu", "scorn, despise, contempt", "軽蔑 (keibetsu - contempt)", "努力する人を軽蔑してはならない。", "どりょくするひとをけいべつしてはならない。", "One must never despise a person who makes efforts."],
  ["遵", "ジュン", "jun", "abide by, follow, obey", "遵守 (junshu - compliance)", "社会通念と諸法令を厳格に遵守する。", "しゃかいつうねんとしょほうれいをげんかくにじゅんしゅする。", "Strictly comply with social norms and regulations."],
  ["謹", "キン / つつし・む", "kin / tsutsushi-mu", "discreet, reverently, humble", "謹慎 (kinshin - suspension, remorse)", "謹んで新春のお慶びを申し上げます。", "つつしんでしんしゅんのおよろこびをもうしあげます。", "I respectfully express new year greetings."],
  ["慎", "シン / つつし・む", "shin / tsutsushi-mu", "prudence, humility, discretion", "慎重 (shinchou - prudence)", "言葉を選んで慎重に話す。", "ことばをえらんでしんちょうにはなす。", "Speak with prudence choosing words carefully."],
  ["畏", "イ / おそ・れる", "i / oso-reru", "fear, majestic, awe", "畏怖 (ifu - awe, reverence)", "雄大な大自然に畏怖の念を抱く。", "ゆうだいなだいしぜんにいふのねんをいだく。", "Harbor awe for magnificent nature."],
  ["忌", "キ / い・む、い・まわしい", "ki / i-mu, i-mawashii", "mourning, abhor, detest", "忌避 (kihi - evasion)", "危険な行為を忌避する。", "きけんなこういをきひする。", "Avoid dangerous actions."],
  ["傲", "ゴウ", "gou", "be proud, arrogant", "傲慢 (gouman - arrogance)", "決して傲慢にならず謙虚でいる。", "けっしてごうまんにならずけんきょでいる。", "Stay humble without ever becoming arrogant."],
  ["慢", "マン", "man", "ridicule, lazy, pride", "慢心 (manshin - overconfidence)", "成功に慢心せず精進を続ける。", "せいこうにまんしんせずしょうじんをつづける。", "Continue devotion without becoming overconfident in success."],
  ["謙", "ケン", "ken", "self-effacing, humble", "謙虚 (kenkyo - modesty)", "常に謙虚な姿勢を大切にする。", "つねにけんきょなしせいをたいせつにする。", "Always value a modest attitude."],
  ["遜", "ソン / へりくだ・る", "son / herikuda-ru", "humble, modest", "謙遜 (kenson - humility)", "褒められても謙遜する。", "ほめられてもけんそんする。", "Be humble even when praised."],
  ["緻", "チ", "chi", "fine, minute, dense", "緻密 (chimitsu - minute, detailed)", "緻密な計算に基づいて設計する。", "ちみつなけいさんにもとづいてせっけいする。", "Design based on minute calculations."],
  ["密", "ミツ / ひそ・か", "mitsu / hiso-ka", "dense, secret, strict", "精密 (seimitsu - precision)", "精密機械の点検を行う。", "せいみつきかいのてんけんをおこなう。", "Conduct inspection of precision machinery."],
  ["鬱", "ウツ / ふさ・ぐ", "utsu / fusa-gu", "gloom, depression, luxuriance", "憂鬱 (yuuutsu - melancholy)", "鬱蒼とした森を抜ける。", "うっそうとしたもりをぬける。", "Pass through a dense, lush forest."],
  ["憂", "ユウ / うれ・える、う・い", "yuu / ure-eru, u-i", "melancholy, grieve", "憂慮 (yuuryo - anxiety)", "将来の環境問題を深く憂慮する。", "しょうらいのかんきょうもんだいをふかくゆうりょする。", "Deeply worry over future environmental problems."],
  ["慮", "リョ / おもんぱか・る", "ryo / omonpaka-ru", "prudence, thought, deliberate", "配慮 (hairyo - consideration)", "周囲の人々に温かく配慮する。", "しゅういのひとびとにあたたかくはいりょする。", "Warmly show consideration to people around."],
  ["篤", "トク", "toku", "fervent, kind, cordial", "篤志 (tokushi - benevolence)", "篤実な人柄が評判を呼ぶ。", "とくじつなひとがらがひょうばんをよぶ。", "Sincere and cordial character gains reputation."]
];

for (const row of n1Master) n1.add(...row);
n1.save('n1.json');
