const path = require('path');
const { compileLevel } = require('./kanji_compiler_helper');

const n3Data = [
  // Politics, Law, Society
  ["政", "セイ、ショウ / まつりごと", "sei, shou / matsurigoto", "politics, government", "政治 (seiji - politics)", "国の政治に関心を持つ。", "くにのせいじにかんしんをもつ。", "Take interest in national politics."],
  ["経", "ケイ、キョウ / へ・る", "kei, kyou / he-ru", "pass through, manage, longitude", "経済 (keizai - economy)", "世界経済の動向を調べる。", "せかいけいざいのどうこうをしらべる。", "Investigate trends in the world economy."],
  ["済", "サイ、ザイ / す・む、す・ます", "sai, zai / su-mu, su-masu", "settle, relieve, finish", "経済 (keizai - economy)", "支払いを手早く済ませる。", "しはらいをとばやくすませる。", "Finish payments quickly."],
  ["歴", "レキ", "reki", "curriculum, passage of time", "歴史 (rekishi - history)", "日本の古代歴史を学ぶ。", "にほんのこだいれきしをまなぶ。", "Study ancient Japanese history."],
  ["史", "シ", "shi", "history, chronicle", "歴史 (rekishi - history)", "近代史の講義を聴く。", "きんだいしのこうぎをきく。", "Listen to a lecture on modern history."],
  ["育", "イク / そだ・つ、そだ・てる", "iku / soda-tsu, soda-teru", "bring up, grow up, educate", "教育 (kyouiku - education)", "子どもを健やかに育てる。", "こどもをすこやかにそだてる。", "Raise children healthily."],
  ["化", "カ、ケ / ば・ける、ば・かす", "ka, ke / ba-keru, ba-kasu", "change, take form of, influence", "文化 (bunka - culture)", "伝統文化を大切に守る。", "でんとうぶんかをたいせつにまもる。", "Carefully protect traditional culture."],
  ["際", "サイ / きわ", "sai / kiwa", "occasion, side, edge", "国際 (kokusai - international)", "国際交流イベントに参加する。", "こくさいこうりゅういべんとにかんかする。", "Participate in an international exchange event."],
  ["科", "カ", "ka", "department, course, science", "科学 (kagaku - science)", "最新の科学技術を導入する。", "さいしんのかがくぎじゅつをどうにゅうする。", "Introduce the latest scientific technology."],
  ["数", "スウ、ス / かず、かぞ・える", "suu, su / kazu, kazo-eru", "number, count", "数字 (suuji - number, digit)", "参加者の数を数える。", "さんかしゃのかずをかぞえる。", "Count the number of participants."],
  ["記", "キ / しる・す", "ki / shiru-su", "scribe, account, narrate", "記録 (kiroku - record)", "日々の出来事をノートに記録する。", "ひびのできごとをのーとにきろくする。", "Record daily events in a notebook."],
  ["法", "ホウ、ハッ、ホッ", "hou, hatsu, hotsu", "law, rule, method", "法律 (houritsu - law)", "法律を守ることは国民の義務だ。", "ほうりつをまもることはこくみんのぎむだ。", "Obeying the law is a citizen's duty."],
  ["律", "リツ、リチ", "ritsu, richi", "rhythm, law, regulation", "規律 (kiritsu - discipline)", "規律正しい生活習慣を送る。", "きりつただしいせいかつしゅうかんをおくる。", "Lead well-disciplined lifestyle habits."],
  ["制", "セイ", "sei", "system, control, rule", "制度 (seido - system)", "新しい評価制度を導入する。", "あたらしいひょうかせいどをどうにゅうする。", "Introduce a new evaluation system."],
  ["務", "ム / つと・める", "mu / tsuto-meru", "task, duties", "義務 (gimu - duty, obligation)", "公務員の職務を全うする。", "こうむいんのしょくむをまっとうする。", "Fulfill the duties of a public servant."],
  ["役", "ヤク、エキ", "yaku, eki", "duty, role, service", "主役 (shuyaku - leading role)", "舞台で主役を立派に演じる。", "ぶたいでしゅやくをりっぱにえんじる。", "Splendidly perform the lead role on stage."],
  ["協", "キョウ", "kyou", "co-operation", "協力 (kyouryoku - cooperation)", "全員でお互いに協力し合う。", "ぜんいんでおたがいにきょうりょくしあう。", "Everyone cooperates with each other."],
  ["結", "ケツ / むす・ぶ、ゆ・う", "ketsu / musu-bu, yu-u", "tie, bind, conclude", "結果 (kekka - result)", "努力が良い結果を生んだ。", "どりょくがよいけっかをうんだ。", "Effort produced a good result."],
  ["相", "ソウ、ショウ / あい", "sou, shou / ai", "mutual, minister, aspect", "相談 (soudan - consultation)", "相手の目を見て誠実に話す。", "あいてのめをみてせいじつにはなす。", "Speak sincerely while looking at the other person's eyes."],
  ["談", "ダン", "dan", "discuss, talk", "面談 (mendan - interview)", "進路について先生と面談する。", "しんろについてせんせいとめんだんする。", "Have an interview with the teacher about career path."],
  ["関", "カン / せき、かか・わる", "kan / seki, kaka-waru", "connection, gateway, involve", "関係 (kankei - relation)", "環境問題に強い関心を持つ。", "かんきょうもんだいにつよいかんしんをもつ。", "Have strong interest in environmental problems."],
  ["係", "ケイ / かか・る、かかり", "kei / kaka-ru, kakari", "person in charge, connection", "案内係 (annaigakari - guide)", "係の指示に従って整列する。", "かかりのしじにしたがってせいれつする。", "Line up according to the staff's instructions."],
  ["連", "レン / つ・れる、つら・なる", "ren / tsu-reru, tsura-naru", "take along, lead, join", "連絡 (renraku - contact)", "友達を連れて美術館へ行く。", "ともだちをつれてびじゅつかんへいく。", "Take a friend along to the art museum."],
  ["絡", "ラク / から・む、から・まる", "raku / kara-mu, kara-maru", "entangle, twine, connect", "連絡 (renraku - communication)", "後ほどメールで連絡いたします。", "のちほどめーるでれんらくいたします。", "I will contact you by email later."],
  ["由", "ユ、ユウ / よし", "yu, yuu / yoshi", "reason, cause", "自由 (jiyuu - freedom)", "遅刻の理由を丁寧に話す。", "ちこくのりゆうをていねいにはなす。", "Politely explain the reason for being late."],
  ["報", "ホウ / むく・いる", "hou / muku-iru", "report, news, reward", "報告 (houkoku - report)", "天気予報を確認して傘を持つ。", "てんきよほうをかくにんしてかさをもつ。", "Check the weather forecast and take an umbrella."],
  ["告", "コク / つ・げる", "koku / tsu-geru", "inform, declare, tell", "広告 (koukoku - advertisement)", "新製品の広告を雑誌に出す。", "しんせいひんのこうこくをざっしにだす。", "Place a new product advertisement in a magazine."],
  ["求", "キュウ / もと・める", "kyuu / moto-meru", "request, want, seek", "要求 (youkyuu - demand)", "平和な社会を心から求める。", "へいわなしゃかいをこころからもとめる。", "Seek a peaceful society from the heart."],
  ["期", "キ、ゴ", "ki, go", "period, time, date", "期間 (kikan - period)", "試験の期日が次第に近づく。", "しけんのきじつがしだいにちかづく。", "The exam date gradually approaches."],
  ["限", "ゲン / かぎ・る", "gen / kagi-ru", "limit, restrict", "限界 (genkai - limit)", "時間には限りがあるため急ぐ。", "じかんにはかぎりがあるためいそぐ。", "Hurry because time has a limit."],
  ["基", "キ / もと、もとい", "ki / moto, motoi", "fundamentals, base", "基本 (kihon - foundation)", "文法の基本をしっかり身につける。", "ぶんぽうのきほんをしっかりみにつける。", "Firmly master the basics of grammar."],
  ["準", "ジュン", "jun", "semi-, associate, standard", "準備 (junbi - preparation)", "標準的な手順に従い作業する。", "ひょうじゅんてきなてじゅんにしたがいさぎょうする。", "Work following standard procedures."],
  ["備", "ビ / そな・える、そな・わる", "bi / sona-eru, sona-waru", "equip, provision, prepare", "準備 (junbi - preparation)", "自然災害に備えて非常食を用意する。", "しぜんさいがいにそなえてひじょうしょくをよういする。", "Prepare emergency food in preparation for natural disasters."],
  ["調", "チョウ / しら・べる、ととの・う", "chou / shira-beru, totono-u", "tune, tone, investigate", "調査 (chousa - survey)", "辞書で単語の意味を詳しく調べる。", "じしょでたんごのいみをくわしくしらべる。", "Look up word meanings in detail using a dictionary."],
  ["査", "サ", "sa", "investigate, examine", "審査 (shinsa - judging, inspection)", "パスポートの入国審査を受ける。", "ぱすぽーとのにゅうこくしんさをうける。", "Undergo passport entry inspection."],
  ["約", "ヤク", "yaku", "promise, approximately", "約束 (yakusoku - promise)", "約一時間歩いて駅に着いた。", "やくいちじかんあるいてえきについた。", "Arrived at the station after walking for approximately one hour."],
  ["束", "ソク / たば、たば・ねる", "soku / taba, taba-neru", "bundle, sheath, bind", "花束 (hanataba - bouquet)", "感謝の花束を先生に贈る。", "かんしゃのはなたばをせんせいにおくる。", "Gift a bouquet of flowers in gratitude to the teacher."],
  ["必", "ヒツ / かなら・ず", "hitsu / kanara-zu", "invariable, certain, inevitable", "必要 (hitsuyou - necessary)", "必ず夢を叶えると誓う。", "かならずゆめをかなえるとちかう。", "Vow to definitely make dreams come true."],
  ["要", "ヨウ / い・る、かなめ", "you / i-ru, kaname", "need, vital point", "重要 (juuyou - important)", "重要な書類を金庫に保管する。", "じゅうようなしょるいをきんこにほかんする。", "Store important documents in a safe."],
  ["想", "ソウ、ソ / おも・う", "sou, so / omo-u", "concept, think, idea", "想像 (souzou - imagination)", "未来の平和な世界を想う。", "みらいのへいわなせかいをおもう。", "Envision a peaceful future world."],
  ["像", "ゾウ", "zou", "statue, picture, image", "映像 (eizou - video, image)", "高画質な映像を楽しむ。", "こうがしつなえいぞうをたのしむ。", "Enjoy high-definition video."],
  ["受", "ジュ / う・ける、う・かる", "ju / u-keru, u-karu", "accept, undergo, catch", "受験 (juken - taking exam)", "希望の学校を受験する。", "きぼうのがっこうをじゅけんする。", "Take entrance exams for the desired school."],
  ["付", "フ / つ・ける、つ・く", "fu / tsu-keru, tsu-ku", "adhere, attach, append", "受付 (uketsuke - reception)", "名札を胸のポケットに付ける。", "なふだをむねのぽけっとにつける。", "Attach the name badge to the chest pocket."],
  ["解", "カイ、ゲ / と・く、と・ける", "kai, ge / to-ku, to-keru", "unravel, notes, solve", "解決 (kaiketsu - solution)", "複雑なパズルを解く。", "ふくざつなぱずるをとく。", "Solve a complex puzzle."],
  ["説", "セツ / と・く", "setsu / to-ku", "opinion, theory, explain", "説明 (setsumei - explanation)", "問題の解き方を分かりやすく説明する。", "もんだいのときかたをわかりやすくせつめいする。", "Explain how to solve the problem clearly."],
  ["向", "コウ / む・く、む・ける", "kou / mu-ku, mu-keru", "yonder, face, turn toward", "方向 (houkou - direction)", "前をしっかり向いて進む。", "まえをしっかりむいてすすむ。", "Advance looking straight ahead."],
  ["進", "シン / すす・む、すす・める", "shin / susu-mu, susu-meru", "advance, proceed, progress", "進歩 (shinpo - progress)", "毎日一歩ずつ前に進む。", "まいにちいっぽずつまえにすすむ。", "Move forward one step at a time every day."],
  ["退", "タイ / しりぞ・く", "tai / shirizo-ku", "retreat, withdraw, resign", "引退 (intai - retirement)", "現役選手を引退する。", "げんえきせんしゅをいんたいする。", "Retire as an active athlete."],
  ["返", "ヘン / かえ・す、かえ・る", "hen / kae-su, kae-ru", "return, answer, fade", "返事 (henji - reply)", "本を図書館のカウンターに返す。", "ほんをとしょかんのかうんたーにかえす。", "Return the book to the library counter."],
  ["客", "キャク、カク", "kyaku, kaku", "guest, visitor, customer", "乗客 (joukyaku - passenger)", "大切なお客様を笑顔で迎える。", "たいせつなおきゃくさまをえがおでむかえる。", "Welcome important customers with a smile."],
  ["席", "セキ / むしろ", "seki / mushiro", "seat, mat, occasion", "指定席 (shiteiseki - reserved seat)", "新幹線の指定席を予約する。", "しんかんせんのしていせきをよやくする。", "Reserve a reserved seat on the Shinkansen."],
  ["勝", "ショウ / か・つ、まさ・る", "shou / ka-tsu, masa-ru", "victory, win, excel", "勝利 (shouri - victory)", "決勝戦で最後まで戦い勝つ。", "けっしょうせんでさいごまでたたかいかつ。", "Fight until the end and win in the final."],
  ["負", "フ / ま・ける、お・う", "fu / ma-keru, o-u", "lose, owe, assume", "勝負 (shoubu - match)", "負けても諦めずに再挑戦する。", "まけてもあきらめずにさいちょうせんする。", "Retry without giving up even if losing."],
  ["争", "ソウ / あらそ・う", "sou / arasou", "contend, dispute, argue", "競争 (kyousou - competition)", "無駄な争いを避けて話し合う。", "むだなあらそいをさけてはなしあう。", "Avoid pointless disputes and talk it through."],
  ["戦", "セン / たたか・う", "sen / tataka-u", "war, battle, match", "作戦 (sakusen - tactics)", "困難な壁に勇敢に立ち向かい戦う。", "こんなんなかべにゆうかんにたちむかいたたかう。", "Bravely face and fight against difficult barriers."],
  ["初", "ショ / はじ・め、はつ", "sho / haji-me, hatsu", "first time, beginning", "初心 (shoshin - original intention)", "初級から上級まで段階的に学ぶ。", "しょきゅうからじょうきゅうまでだんかいてきにまなぶ。", "Learn step by step from beginner to advanced."],
  ["終", "シュウ / お・わる、お・える", "shuu / o-waru, o-eru", "end, finish", "最終 (saishuu - final)", "本日の講義が無事に終わった。", "ほんじつのこうぎがぶじにおわった。", "Today's lecture safely finished."],
  ["最", "サイ / もっと・も", "sai / motto-mo", "utmost, most, extreme", "最高 (saikou - best, supreme)", "世界で最も美しい景色を眺める。", "せかいでもっともうつくしいけしきをながめる。", "Gaze upon the most beautiful scenery in the world."],
  ["級", "キュウ", "kyuu", "class, rank, grade", "学級 (gakkyuu - school class)", "日本語能力試験でN3級に合格する。", "にほんごのうりょくしけんでN3きゅうにごうかくする。", "Pass JLPT N3 level certification."],
  ["比", "ヒ / くら・べる", "hi / kura-beru", "compare, race, ratio", "比較 (hikaku - comparison)", "二つの製品の性能を比べる。", "ふたつのせいひんのせいのうをくらべる。", "Compare the performance of the two products."],
  ["較", "カク", "kaku", "contrast, compare", "比較 (hikaku - comparison)", "価格と品質を比較検討する。", "かかくとひんしつをひかくけんとうする。", "Compare and evaluate price and quality."],
  ["点", "テン / つ・ける", "ten / tsu-keru", "point, dot, mark", "満点 (manten - perfect score)", "小テストで満点を取る。", "しょうてすとでまんてんをとる。", "Get a perfect score on the quiz."],
  ["直", "チョク、ジキ / ただ・ちに、なお・す", "choku, jiki / tada-chini, nao-su", "straight, fix, direct", "直接 (chokusetsu - direct)", "壊れた時計を丁寧に直す。", "こわれたとけいにていねいになおす。", "Carefully repair the broken clock."],
  ["接", "セツ / つ・ぐ", "setsu / tsu-gu", "touch, contact, join", "面接 (mensetsu - interview)", "就職試験の面接に臨む。", "しゅうしょくしけんのめんせつにのぞむ。", "Attend the job examination interview."],
  ["面", "メン / おもて、つら", "men / omote, tsura", "mask, face, aspect", "正面 (shoumen - front)", "建物の正面玄関に集合する。", "たてもののしょうめんげんかんにしゅうごうする。", "Gather at the front entrance of the building."],
  ["反", "ハン / そ・る、かえ・す", "han / so-ru, kae-su", "anti-, bend, oppose", "違反 (ihan - violation)", "交通ルールに違反しない。", "こうつうるーるにいはんしない。", "Do not violate traffic rules."],
  ["対", "タイ、ツイ", "tai, tsui", "vis-a-vis, opposite, pair", "対話 (taiwa - dialogue)", "相手に対して敬意を持って接する。", "あいてにたいしてけいいをもってせっする。", "Interact with respect toward the other person."],
  ["側", "ソク / かわ、そば", "soku / kawa, soba", "side, lean, oppose", "両側 (ryougawa - both sides)", "川の両側に桜の木が並ぶ。", "かわのりょうがわにさくらのきがならぶ。", "Cherry trees line both sides of the river."],
  ["投", "トウ / な・げる", "tou / na-geru", "throw, discard, invest", "投資 (toushi - investment)", "未来のために自己投資を行う。", "みらいのためにじことうしをおこなう。", "Make self-investments for the future."],
  ["票", "ヒョウ", "hyou", "ballot, label, ticket", "投票 (touhyou - voting)", "大切な一票を清き心で投じる。", "たいせつないっぴょうをきよきこころでとうじる。", "Cast an important vote with a clear conscience."],
  ["選", "セン / えら・ぶ", "sen / era-bu", "elect, choose, select", "選択 (sentaku - choice)", "自分にとって最良の進路を選ぶ。", "じぶんにとってさいりょうのしんろをえらぶ。", "Choose the best path for oneself."],
  ["挙", "キョ / あ・げる", "kyo / a-geru", "raise, plan, actions", "選挙 (senkyo - election)", "質問があるときは手を挙げる。", "しつもんがあるときはてをあげる。", "Raise hand when you have a question."],
  ["包", "ホウ / つつ・む", "hou / tsutsu-mu", "wrap, pack, cover", "包装 (housou - wrapping)", "贈り物を綺麗な和紙で包む。", "おくりものをきれいなわしでつつむ。", "Wrap the gift in beautiful Japanese paper."],
  ["装", "ソウ / よそお・う", "sou / yosoo-u", "attire, dress, equip", "服装 (fukusou - garments)", "面接には清潔な服装で臨む。", "めんせつにはせいけつなふくそうでぞむ。", "Attend the interview in neat, clean clothes."],
  ["展", "テン", "ten", "unfold, expand", "発展 (hatten - development)", "科学技術が急速に発展する。", "かがくぎじゅつがきゅうそくにはってんする。", "Science and technology develop rapidly."],
  ["示", "ジ、シ / しめ・す", "ji, shi / shime-su", "show, indicate, point out", "提示 (teiji - presentation)", "身分証明書を受付で提示する。", "みぶんしょうめいしょをうけつけでていじする。", "Present identification at the reception desk."],
  ["存", "ソン、ゾン", "son, zon", "exist, know, suppose", "生存 (seizon - survival)", "ご存知の通り計画は順調です。", "ごぞんじのとおりけいかくはじゅんちょうです。", "As you know, the plan is on track."],
  ["在", "ザイ / あ・る", "zai / a-ru", "exist, located in", "存在 (sonzai - existence)", "家族の存在が大きな支えになる。", "かぞくのそんざいがおおきなささえになる。", "The presence of family is a great support."],
  ["現", "ゲン / あらわ・れる", "gen / arawa-reru", "present, existing, appear", "現在 (genzai - present time)", "現在地をスマートフォンで確認する。", "げんざいちをすまーとふぉんでかくにんする。", "Check the current location on the smartphone."],
  ["組", "ソ / く・む、くみ", "so / ku-mu, kumi", "association, assemble, braid", "番組 (bangumi - program)", "テレビで教育番組を見る。", "てれびできょういくばんぐみをみる。", "Watch an educational program on television."],
  ["織", "ショク / お・る", "shoku / o-ru", "weave, fabric", "組織 (soshiki - organization)", "伝統的な技法で布を織る。", "でんとうてきなぎほうでぬのをおる。", "Weave cloth using traditional techniques."],
  ["変", "ヘン / か・わる、か・える", "hen / ka-waru, ka-eru", "unusual, change, strange", "大変 (taihen - tough, very)", "生活環境が大きく変わる。", "せいかつかんきょうがおおきくかわる。", "Living environment changes greatly."],
  ["信", "シン", "shin", "faith, trust, message", "信用 (shin'you - trust)", "仲間との信頼関係を築く。", "なかまとのしんらいかんけいをきずく。", "Build relations of trust with peers."],
  ["号", "ゴウ", "gou", "nickname, number, item", "番号 (bangou - number)", "電話番号をメモ帳に控える。", "でんわばんごうをめもちょうにひかえる。", "Take note of the phone number in the memo pad."],
  ["置", "チ / お・く", "chi / o-ku", "placement, put, establish", "位置 (ichi - location)", "荷物を棚の上に置く。", "にもつをたなのうえにおく。", "Place the package onto the shelf."],
  ["位", "イ / くらい", "i / kurai", "rank, grade, about", "順位 (jun'i - ranking)", "大会で第一位を獲得する。", "たいかいでだいいちいをつくとくする。", "Achieve first place in the tournament."],
  ["副", "フク", "fuku", "vice-, assistant, copy", "副詞 (fukushi - adverb)", "日本語の副詞の使い方を覚える。", "にほんごのふくしのつかいかたをおぼえる。", "Learn the usage of Japanese adverbs."],
  ["授", "ジュ / さず・ける", "ju / sazu-keru", "impart, instruct, award", "授業 (jugyou - lesson)", "大学で専門的な講義を授与される。", "だいがくでせんもんてきなこうぎをじゅよされる。", "Be taught specialized lectures at university."],
  ["配", "ハイ / くば・る", "hai / kuba-ru", "distribute, spouse", "心配 (shinpai - worry)", "プリントをクラス全員に配る。", "ぷりんとをくらすぜんいんにくばる。", "Distribute handouts to the whole class."],
  ["達", "タツ / たち", "tatsu / tachi", "accomplished, reach, plural", "発達 (hattatsu - development)", "文明が高度に発達する。", "ぶんめいがこうどにはったつする。", "Civilization develops to a high degree."],
  ["届", "カイ / とど・く", "kai / todo-ku", "deliver, reach, report", "届け出 (todokede - notification)", "大切な手紙が無事に届いた。", "たいせつなてがみがぶじにとどいた。", "The important letter safely arrived."],
  ["宅", "タク", "taku", "home, house, residence", "住宅 (juutaku - housing)", "静かな住宅街に暮らす。", "しずかなじゅうたくがいにくらす。", "Live in a quiet residential district."],
  ["宿", "シュク / やど", "shuku / yado", "inn, lodge, dwell", "宿題 (shukudai - homework)", "毎日の宿題をしっかり終わらせる。", "まいにちのしゅくだいをしっかりおわらせる。", "Firmly finish daily homework."],
  ["泊", "ハク / と・まる", "haku / to-maru", "overnight stay", "外泊 (gaihaku - staying overnight away)", "京都の旅館に二泊する。", "きょうとのりょかんににはくする。", "Stay two nights at a Kyoto inn."],
  ["乗", "ジョウ / の・る", "jou / no-ru", "ride, board, multiply", "乗車 (jousha - boarding)", "朝の通勤電車に乗る。", "あさのつうきんでんしゃにのる。", "Ride the morning commuter train."],
  ["降", "コウ / お・りる、ふ・る", "kou / o-riru, fu-ru", "descend, precipitate, fall", "降雪 (kousetsu - snowfall)", "静かに雪が降り積もる。", "しずかにゆきがふりつもる。", "Snow silently falls and accumulates."],
  ["呼", "コ / よ・ぶ", "ko / yo-bu", "call, invite, breathe", "点呼 (tenko - roll call)", "大きな声で名前を呼ぶ。", "おおきなこえでなまえをよぶ。", "Call out the name with a loud voice."],
  ["吸", "キュウ / す・う", "kyuu / su-u", "suck, inhale", "吸収 (kyuushuu - absorption)", "知識をスポンジのように吸収する。", "ちしきをすぽんじのようにきゅうしゅうする。", "Absorb knowledge like a sponge."],
  ["息", "ソク / いき", "soku / iki", "breath, son, interest", "休息 (kyuusoku - rest)", "深呼吸をして心を落ち着かせる。", "しんこきゅうをしてこころをおちつかせる。", "Take a deep breath and calm the mind."],
  ["忘", "ボウ / わす・れる", "bou / wasu-reru", "forget", "忘年会 (bounenkai - year-end party)", "恩師への感謝を忘れない。", "おんしへのかんしゃをわすれない。", "Never forget gratitude to one's mentor."],
  ["忙", "ボウ / いそが・しい", "bou / isoga-shii", "busy, hurried", "繁忙 (hanbou - busy season)", "年度末で仕事がとても忙しい。", "ねんどまつでしごとがとてもいそがしい。", "Work is very busy at fiscal year end."],
  ["恐", "キョウ / おそ・れる", "kyou / oso-reru", "fear, dread, awe", "恐縮 (kyoushuku - humble apologies)", "失敗を恐れずに挑戦し続ける。", "しっぱいをおそれずにてちょうせんしつづける。", "Keep challenging without fearing failure."],
  ["怖", "フ / こわ・い", "fu / kowa-i", "scary, dreadful", "恐怖 (kyoufu - fear)", "暗い夜道を歩くのは少し怖い。", "くらいよみちをあるくのはすこしこわい。", "Walking dark night roads is a bit scary."],
  ["怒", "ド / おこ・る", "do / oko-ru", "angry, be indignant", "怒気 (doki - anger)", "理由もなく怒ってはいけない。", "りゆうもなくおこってはいけない。", "One should not get angry without reason."],
  ["悲", "ヒ / かな・しい", "hi / kana-shii", "sad, sorrow, grieve", "悲劇 (higeki - tragedy)", "悲しいニュースに胸を痛める。", "かなしいにゅーすにむねをいためる。", "Pained at heart by the sad news."],
  ["喜", "キ / よろこ・ぶ", "ki / yoroko-bu", "rejoice, take pleasure in", "喜劇 (kigeki - comedy)", "友達の成功を心から喜ぶ。", "ともだちのせいこうをこころからよろこぶ。", "Genuinely rejoice in a friend's success."],
  ["笑", "ショウ / わら・う", "shou / wara-u", "laugh, smile", "爆笑 (bakushou - roar of laughter)", "楽しい冗談を聞いて笑う。", "たのしいじょうだんをきいてわらう。", "Laugh upon hearing a fun joke."],
  ["泣", "キュウ / な・く", "kyuu / na-ku", "cry, weep", "感泣 (kankyuu - crying with emotion)", "映画のラストシーンで思わず泣く。", "えいがのらすとしーんでおもわずなく。", "Involuntarily cry at the movie's last scene."],
  ["苦", "ク / くる・しい、にが・い", "ku / kuru-shii, niga-i", "suffering, bitter, hard", "苦心 (kushin - pains, effort)", "苦しい練習を乗り越えて優勝した。", "くるしいれんしゅうをのりこえてゆうしょうした。", "Overcame arduous training and won the championship."],
  ["痛", "ツウ / いた・い", "tsuu / ita-i", "pain, ache, hurt", "痛感 (tsuukan - feeling keenly)", "健康の大切さを痛感する。", "けんこうのたいせつさをつうかんする。", "Keenly feel the importance of health."],
  ["熱", "ネツ / あつ・い", "netsu / atsu-i", "heat, temperature, fever", "熱心 (nesshin - enthusiastic)", "熱心に日本語の勉強に打ち込む。", "ねっしんににほんごのべんきょうにうちこむ。", "Enthusiastically devote oneself to studying Japanese."],
  ["冷", "レイ / つめ・たい", "rei / tsume-tai", "cool, cold, chill", "冷蔵 (reizou - refrigeration)", "冷静に物事を判断する。", "れいせいにものごとをはんだんする。", "Judge matters calmly."],
  ["温", "オン / あたた・かい", "on / atata-kai", "warm", "温泉 (onsen - hot spring)", "温かい温泉に入ってリラックスする。", "あたたかいおんせんにはいってりらっくすする。", "Enter a warm hot spring and relax."],
  ["暖", "ダン / あたた・かい", "dan / atata-kai", "warmth", "暖房 (danbou - heating)", "春の暖かい日差しが心地よい。", "はるのあたたかいひざしがここちよい。", "The warm spring sunshine feels pleasant."],
  ["涼", "リョウ / すず・しい", "ryou / suzu-shii", "refreshing, cool", "夕涼み (yuusuzumi - cooling in evening)", "夕暮れの涼しい風を楽しむ。", "ゆうぐれのすずしいかぜをたのしむ。", "Enjoy the cool evening breeze."],
  ["甘", "カン / あま・い", "kan / ama-i", "sweet, pamper", "甘酒 (amazake - sweet sake)", "甘い果物を美味しくいただく。", "あまいくものをおいしくいただく。", "Deliciously enjoy sweet fruit."],
  ["辛", "シン / から・い", "shin / kara-i", "spicy, hot, painful", "辛口 (karakuchi - dry taste, biting)", "辛いスパイスの効いたカレーを食べる。", "からいすぱいすのきいたかれーをたべる。", "Eat curry seasoned with spicy seasonings."],
  ["塩", "エン / しお", "en / shio", "salt", "塩分 (enbun - salt content)", "塩分を控えめにした健康的な料理。", "えんぶんをひかえめにしたけんこうてきなりょうり。", "Healthy dishes with restrained salt content."],
  ["油", "ユ / あぶら", "yu / abura", "oil, fat", "油断 (yudan - carelessness)", "油断せずに最後まで集中する。", "ゆだんせずにさいごまでしゅうちゅうする。", "Stay focused without letting down one's guard until the end."],
  ["酒", "シュ / さけ", "shu / sake", "alcoholic drink, sake", "酒屋 (sakaya - liquor store)", "地元の銘酒を味わう。", "じもとのめいしゅをあじわう。", "Savor renowned local sake."],
  ["茶", "チャ、サ", "cha, sa", "tea", "喫茶 (kissa - tearoom)", "静かな喫茶店で本を読む。", "しずかなきっさてんでほんをよむ。", "Read a book at a quiet cafe."],
  ["米", "ベイ、マイ / こめ", "bei, mai / kome", "rice, USA, meter", "米国 (beikoku - USA)", "美味しいお米を丁寧に炊く。", "おいしいおこめにていねいにたく。", "Cook delicious rice carefully."],
  ["肉", "ニク", "niku", "meat, flesh", "筋肉 (kinniku - muscle)", "筋力トレーニングで筋肉を鍛える。", "きんりょくとれーにんぐできんにくをきたえる。", "Train muscles through strength training."],
  ["魚", "ギョ / さかな", "gyo / sakana", "fish", "金魚 (kingyo - goldfish)", "水族館で色とりどりの魚を見る。", "すいぞくかんでいろとりどりのさかなをみる。", "Look at colorful fish at the aquarium."],
  ["鳥", "チョウ / とり", "chou / tori", "bird, chicken", "白鳥 (hakuchou - swan)", "湖で優雅に泳ぐ白鳥を眺める。", "みずうみでゆうがにおよぐはくちょうをながめる。", "Gaze at swans swimming elegantly on the lake."],
  ["犬", "ケン / いぬ", "ken / inu", "dog", "番犬 (banken - watchdog)", "賢い犬が家を守っている。", "かしこいいぬがいえをまもっている。", "A clever dog protects the house."],
  ["虫", "チュウ / むし", "chuu / mushi", "insect, bug, temper", "害虫 (gaichuu - harmful insect)", "秋の夜に虫の音を聴く。", "あきのよるにむしのねをきく。", "Listen to the sounds of insects in autumn nights."],
  ["草", "ソウ / くさ", "sou / kusa", "grass, weeds, herbs", "薬草 (yakusou - medicinal herb)", "庭の草むしりをして整える。", "にわのくさむしりをしてととのえる。", "Weed the garden and tidy it up."],
  ["林", "リン / はやし", "rin / hayashi", "grove, forest", "竹林 (chikurin - bamboo grove)", "静かな竹林の道を散策する。", "しずかなちくりんのみちをさんさくする。", "Stroll through a quiet bamboo grove path."],
  ["森", "シン / もり", "shin / mori", "forest, woods", "森林浴 (shinrin'yoku - forest bathing)", "豊かな森で森林浴を楽しむ。", "ゆたかなもりでしんりんよくをたのしむ。", "Enjoy forest bathing in a rich forest."],
  ["池", "チ / いけ", "chi / ike", "pond, reservoir", "溜池 (tameike - reservoir)", "庭園の池に睡蓮が咲いている。", "ていえんのいけにすいれんがさいている。", "Water lilies bloom in the garden pond."],
  ["海", "カイ / うみ", "kai / umi", "sea, ocean", "海水 (kaisui - seawater)", "青く澄んだ海を船で渡る。", "あおくすんだうみをふねでわたる。", "Cross the clear blue sea by boat."],
  ["島", "トウ / しま", "tou / shima", "island", "無人島 (mujintou - uninhabited island)", "美しい離島を船で巡る。", "うつくしいりとうをふねでめぐる。", "Tour beautiful remote islands by boat."],
  ["岸", "ガン / きし", "gan / kishi", "beach, coast, bank", "湾岸 (wangan - gulf coast)", "夕暮れの海岸を静かに散歩する。", "ゆうぐれのかいがんをしずかにさんぽする。", "Quietly stroll the seashore at twilight."],
  ["岩", "ガン / いわ", "gan / iwa", "boulder, rock, cliff", "岩場 (iwaba - rocky area)", "険しい岩山を登る。", "けわしいいわやまをのぼる。", "Climb a steep rocky mountain."],
  ["港", "コウ / みなと", "kou / minato", "harbor, port", "港町 (minatomachi - port town)", "情緒ある港町の風景を楽しむ。", "じょうちょあるみなとまちのふうけいをたのしむ。", "Enjoy the atmosphere of the port town landscape."]
];

compileLevel('N3', n3Data, path.join(__dirname, '../data/kanji/n3.json'));
