const path = require('path');
const { compileLevel } = require('./kanji_compiler_helper');

const n1Data = [
  ["概", "ガイ / おおむ・ね", "gai / oomu-ne", "outline, condition, general", "概念 (gainen - concept)", "新しい哲学的な概念を考察する。", "あたらしいてつがくてきながいねんをこうさつする。", "Examine a new philosophical concept."],
  ["妥", "ダ", "da", "gentle, peace, appropriate", "妥当 (datou - valid, proper)", "その意見には妥当性がある。", "そのいけんにはだとうせいがある。", "There is validity to that opinion."],
  ["矛", "ム、ボウ / ほこ", "mu, bou / hoko", "halberd, spear", "矛盾 (mujun - contradiction)", "言動の矛盾を指摘される。", "げんどうのむじゅんをしてきされる。", "Have contradictions in words and deeds pointed out."],
  ["盾", "ジュン / たて", "jun / tate", "shield, escutcheon", "矛盾 (mujun - inconsistency)", "矛と盾の故事から学ぶ。", "ほことたてのこじからまなぶ。", "Learn from the historical fable of spear and shield."],
  ["欺", "ギ / あざむ・く", "gi / azamu-ku", "deceit, cheat, delude", "欺瞞 (giman - deception)", "敵の目を欺いて逃走する。", "てきのめをあざむいてとうそうする。", "Deceive the enemy's eyes and escape."],
  ["瞞", "マン", "man", "deceive, delude", "欺瞞 (giman - deception)", "欺瞞に満ちた説明に抗議する。", "ぎまんにみちたせつめいにこうぎする。", "Protest explanations filled with deceit."],
  ["懸", "ケン、ケ / か・ける", "ken, ke / ka-keru", "suspend, hang, depend", "懸念 (kenen - concern, anxiety)", "景気の後退が深く懸念される。", "けいきのこうたいがふかくけねんされる。", "Economic decline is deeply feared."],
  ["念", "ネン", "nen", "wish, sense, idea, thought", "記念 (kinen - commemoration)", "感謝の念を常に心に抱く。", "かんしゃのねんをつねにこころにいだく。", "Always hold feelings of gratitude in one's heart."],
  ["脆", "ゼイ / もろ・い", "zei / moro-i", "brittle, fragile, frail", "脆弱 (zeijaku - vulnerable, frail)", "セキュリティの脆弱性を修正する。", "せきゅりてぃのぜいじゃくせいをしゅうせいする。", "Fix the security vulnerability."],
  ["弱", "ジャク / よわ・い", "jaku / yowa-i", "weak, frail", "弱点 (jakuten - weak point)", "自分の弱点を克服する。", "じぶんのじゃくてんをこくふくする。", "Overcome one's own weaknesses."],
  ["顕", "ケン / あきらか", "ken / akiraka", "manifest, prominent, clear", "顕著 (kencho - remarkable, striking)", "温暖化の影響が顕著に現れる。", "おんだんかのえいきょうがけんちょにあらわれる。", "The impact of global warming appears remarkably."],
  ["著", "チョ、チャク / あらわ・す、いちじる・しい", "cho, chaku / arawa-su, ichijiru-shii", "renowned, publish, write", "著名 (chomei - famous, prominent)", "著名な学者による論文を読む。", "ちょめいながくしゃによるろんぶんをよむ。", "Read a paper by a prominent scholar."],
  ["模", "モ", "mo", "pattern, imitation", "模索 (mosaku - groping for)", "解決のための道を模索する。", "かいけつのためのみちをもさくする。", "Grope for a path toward a solution."],
  ["索", "サク", "saku", "cord, rope, search", "検索 (kensaku - search)", "情報をインターネットで検索する。", "じょうほうをいんたーねっとでけんさくする。", "Search for information on the internet."],
  ["瓦", "ガ / かわら", "ga / kawara", "tile, gram", "瓦解 (gakai - collapse)", "古い家の屋根瓦を修復する。", "ふるいいえのやねがわらをしゅうふくする。", "Restore the roof tiles of an old house."],
  ["乖", "カイ / そむ・く", "kai / somu-ku", "diverge, estrange, alienate", "乖離 (kairi - alienation, divergence)", "理想と現実の乖離に悩む。", "りそうとげんじつのかいりになやむ。", "Worry over the divergence between ideal and reality."],
  ["離", "リ / はな・れる、はな・す", "ri / hana-reru, hana-su", "detach, separate, leave", "分離 (bunri - separation)", "故郷を遠く離れて暮らす。", "こきょうをとおくはなれてくらす。", "Live far separated from one's hometown."],
  ["卓", "タク", "taku", "eminent, table, desk", "卓越 (takuetsu - excellence)", "卓越した技術を持つ職人。", "たくえつしたぎじゅつをもつしょくにん。", "An artisan possessing superior craftsmanship."],
  ["越", "エツ / こ・える", "etsu / ko-eru", "surpass, cross over, exceed", "超越 (chouetsu - transcendence)", "国境を越えて人々が助け合う。", "こっきょうをこえてひとびとがたすけあう。", "People help one another crossing national borders."],
  ["掌", "ショウ / てのひら", "shou / tenohira", "manipulate, palm of hand", "掌握 (shouaku - seize control)", "全権をその手中に掌握する。", "ぜんけんをそのしゅちゅうにしょうあくする。", "Seize all authority into one's grasp."],
  ["握", "アク / にぎ・る", "aku / nigi-ru", "grip, hold, wield", "握手 (akushu - handshake)", "しっかりと手を握り締める。", "しっかりとてをにぎりしめる。", "Firmly grasp hands."],
  ["看", "カン / み・る", "kan / mi-ru", "watch over, see", "看過 (kanka - overlook)", "不正行為を決して看過しない。", "ふせいこういをけっしてかんかしない。", "Never overlook illicit behavior."],
  ["過", "カ / す・ぎる、あやま・ち", "ka / su-giru, ayama-chi", "overdo, exceed, mistake", "過去 (kako - past)", "過去の経験を未来に活かす。", "かこのけいけんをみらいにいかす。", "Apply past experiences to the future."],
  ["糾", "キュウ", "kyuu", "twist, ask, censure", "糾弾 (kyuudan - denunciation)", "不正を犯した者を厳しく糾弾する。", "ふせいをやかしたものをきびしくきゅうだんする。", "Strictly denounce those who committed malpractice."],
  ["弾", "ダン / ひ・く、たま", "dan / hi-ku, tama", "bullet, bounce, play string", "弾劾 (dangai - impeachment)", "ピアノの鍵盤を軽快に弾く。", "ぴあののけんばんをけいかいにひく。", "Lightly play the keys of the piano."],
  ["克", "コク / か・つ", "koku / ka-tsu", "overcome, skillfully", "克服 (kokufuku - overcoming)", "病気を強い意志で克服する。", "びょうきをつよいいしでこくふくする。", "Overcome illness with a strong will."],
  ["明", "メイ、ミョウ / あか・るい", "mei, myou / aka-rui", "bright, light, clear", "克明 (kokumei - detailed, clear)", "当時の様子を克明に書き記す。", "とうじのようすをこくめいにかきしるす。", "Write down the situation of those days in minute detail."],
  ["拘", "コウ / かにかわ・る", "kou / kani-kawa-ru", "arrest, stick to, detain", "拘束 (kousoku - restriction)", "些細な形式に拘泥しない。", "ささいなけいしきにこうでいしない。", "Do not adhere obstinately to trivial formalities."],
  ["束", "ソク", "soku", "tie, bundle", "約束 (yakusoku - promise)", "規則による拘束を最小限にする。", "きそくによるこうそくをさいしょうげんにする。", "Minimize restriction by regulations."],
  ["示", "ジ", "ji", "indicate, show", "示唆 (shisa - hint, suggestion)", "実験データが重要な事実を示唆する。", "じっけんでーたがじゅうようなじじつをしさする。", "Experimental data suggests an important fact."],
  ["唆", "サ / そそのか・す", "sa / sosonoka-su", "instigate, tempt", "示唆 (shisa - implication)", "今後の指針を示唆する報告。", "こんごのししんをしさするほうこく。", "A report suggesting future guidelines."],
  ["収", "シュウ / おさ・める", "shuu / osa-meru", "take in, obtain, harvest", "収斂 (shuuren - convergence)", "様々な議論が一つの結論に収斂する。", "さまざまなぎろんがひとつのけつろんにしゅうれんする。", "Various debates converge toward one conclusion."],
  ["斂", "レン / おさ・める", "ren / osa-meru", "gather, collect", "収斂 (shuuren - gathering, condensing)", "多様な視点を集約し収斂させる。", "たようなしてんをしゅうやくししゅうれんさせる。", "Integrate and converge diverse viewpoints."],
  ["是", "ゼ / これ", "ze / kore", "just so, right, correct", "是正 (zesei - correction)", "不合理な慣習を是正する。", "ふごうりなかんしゅうをぜせいする。", "Rectify irrational customs."],
  ["正", "セイ、ショウ / ただ・しい", "sei, shou / tada-shii", "correct, righteous", "正直 (shoujiki - honesty)", "常に正しい道を選んで歩む。", "つねにただしいみちをえらんであゆむ。", "Always walk choosing the righteous path."],
  ["拙", "セツ / つたな・い", "setsu / tsutana-i", "clumsy, unskillful, humble", "拙速 (sessoku - quick though rough)", "巧遅より拙速を尊ぶ場合もある。", "こうちよりせっそくをとうとぶばあいもある。", "There are cases where prompt action is valued over slow perfection."],
  ["速", "ソク / はや・い", "soku / haya-i", "quick, fast", "速度 (sokudo - speed)", "迅速な対応を心がける。", "じんそくなたいおうをこころがける。", "Keep prompt response in mind."],
  ["遡", "ソ / さかのぼ・る", "so / sakanobo-ru", "go back, trace to source", "遡及 (sokyuu - retroactive)", "川の流れを上流へと遡る。", "かわのながれをじょうりゅうへとさかのぼる。", "Go up the river towards the upper stream."],
  ["及", "キュウ / およ・ぶ、およ・ぼす", "kyuu / oyo-bu, oyo-bosu", "reach out, exert, extend", "波及 (hakyuu - ripple effect)", "影響が社会全体に及ぶ。", "えいきょうがしゃかいぜんたいにおよぶ。", "The influence extends across society."],
  ["相", "ソウ", "sou", "mutual, aspect", "相殺 (sousai - offset)", "互いの貸借関係を相殺する。", "たがいのたいしゃくかんけいをそうさいする。", "Offset mutual borrowing and lending."],
  ["殺", "サツ、サイ / ころ・す", "satsu, sai / koro-su", "kill, diminish, offset", "相殺 (sousai - cancellation)", "損益を相殺して計算する。", "そんえきをそうさいしてけいさんする。", "Calculate after offsetting gains and losses."],
  ["阻", "ソ / はば・む", "so / haba-mu", "thwart, separate, deter", "阻害 (sogai - obstruction)", "健全な発展を阻害する要因を除く。", "けんぜんなはってんをそがいするよういんをのぞく。", "Eliminate factors that obstruct healthy development."],
  ["害", "ガイ", "gai", "harm, injury, damage", "公害 (kougai - pollution)", "環境に害を与えない技術。", "かんきょうにがいをあたえないぎじゅつ。", "Technology that causes no harm to the environment."],
  ["淘", "トウ / よな・げる", "tou / yona-geru", "select, wash out", "淘汰 (touta - weeding out)", "時代の変化で古い制度が淘汰される。", "じだいのへんかでふるいせいどがとうたされる。", "Old systems are weeded out by changing times."],
  ["汰", "タ", "ta", "luxury, wash out, select", "淘汰 (touta - selection)", "市場競争による自然淘汰。", "しじょうきょうそうによるしぜんとうた。", "Natural selection through market competition."],
  ["踏", "トウ / ふ・む", "tou / fu-mu", "step, trample, carry out", "踏襲 (toushuu - follow precedent)", "前人の輝かしい業績を踏襲する。", "ぜんじんのかがやかしいぎょうせきをとうしゅうする。", "Follow in the illustrious achievements of predecessors."],
  ["襲", "シュウ / おそ・う", "shuu / oso-u", "attack, advance, succeed to", "襲名 (shuumei - succession to a name)", "伝統ある芸名を堂々と襲名する。", "でんとうあるげいめいをどうどうとしゅうめいする。", "Dignifiedly succeed to a traditional stage name."],
  ["頓", "トン / とみ・に", "ton / tomi-ni", "suddenly, bow, pause", "頓挫 (tonza - sudden halt)", "資金不足で建設計画が頓挫した。", "しきんぶそくでけんせつけいかくがとんざした。", "The construction plan stalled due to lack of funds."],
  ["挫", "ザ / くじ・く、くじ・ける", "za / kuji-ku, kuji-keru", "sprain, crush, dampen", "挫折 (zasetsu - setback)", "挫折をバネにしてさらに成長する。", "ざせつをばねにしてさらにせいちょうする。", "Grow even further using setbacks as a springboard."],
  ["破", "ハ / やぶ・る", "ha / yabu-ru", "rend, rip, break", "破綻 (hatan - collapse)", "世界記録を堂々と打ち破る。", "せかいきろくをどうどうとうちやぶる。", "Gloriously break the world record."],
  ["綻", "タン / ほころ・びる", "tan / hokoro-biru", "rip, come undone, smile", "破綻 (hatan - bankruptcy)", "桜のつぼみが春に綻びる。", "さくらのつぼみがはるにほころびる。", "Cherry blossoms buds begin to open in spring."],
  ["比", "ヒ", "hi", "compare", "比肩 (hiken - rival, equal)", "世界最高峰の名作に比肩する。", "せかいさいこうほうのめいさくにひけんする。", "Rivals the world's topmost masterpieces."],
  ["肩", "ケン / かた", "ken / kata", "shoulder", "比肩 (hiken - standing shoulder to shoulder)", "荷物を肩にかついで運ぶ。", "にもつをかたにかついではこぶ。", "Carry the luggage shouldering it on one's back."],
  ["逼", "ヒツ / せま・る", "hitsu / sema-ru", "approach, urgent, pressed", "逼迫 (hippaku - stringency)", "医療供給の体制が逼迫する。", "いりょうきょうきゅうのたいせいがひっぱくする。", "The medical supply structure is severely strained."],
  ["迫", "ハク / せま・る", "haku / sema-ru", "urge, force, imminent", "切迫 (seppaku - tension)", "締切の日時が間近に迫る。", "しめきりのにちじがまぢかにせまる。", "The deadline approaches closely."],
  ["変", "ヘン", "hen", "change", "変容 (henyou - transfiguration)", "社会の価値観が大きく変容する。", "しゃかいのかちかんがおおきくへんようする。", "Social values undergo profound transfiguration."],
  ["包", "ホウ", "hou", "wrap", "包括 (houkatsu - comprehensive)", "包括的な支援プランを策定する。", "ほうかつてきなしえんぷらんをさくていする。", "Formulate a comprehensive support plan."],
  ["括", "カツ / くく・る", "katsu / kuku-ru", "fasten, tie, summarize", "総括 (soukatsu - summary)", "一年の研究成果を総括する。", "いちねんのけんきゅうせいかをそうかつする。", "Summarize the research results of the year."],
  ["補", "ホ", "ho", "supplement", "補完 (hokan - complement)", "お互いの長所で短所を補完する。", "おたがいのちょうしょでたんしょをほかんする。", "Complement each other's weaknesses with strengths."],
  ["完", "カン", "kan", "perfect, completion", "完全 (kanzen - perfection)", "すべての準備が完全に完了した。", "すべてのじゅんびがかんぜんにかんりょうした。", "All preparations have been completely finished."],
  ["萌", "ホウ / も・える", "hou / mo-eru", "sprout, bud, germ", "萌芽 (houga - germ, sprout)", "春の山に草木が一斉に萌え出ずる。", "はるのやまにくさきがいっせいにもえいずる。", "Trees and grass sprout all at once in the spring mountain."],
  ["芽", "ガ / め", "ga / me", "bud, sprout, spear", "発芽 (hatsuga - germination)", "小さな種から新しい芽が出る。", "ちいさなたねからあたらしいめがでる。", "New sprouts emerge from small seeds."],
  ["膨", "ボウ / ふく・らむ", "bou / fuku-ramu", "swell, get fat, expand", "膨張 (bouchou - expansion)", "宇宙は今も膨張を続けている。", "うちゅうはいまもぼうちょうをつづけている。", "The universe continues to expand even now."],
  ["張", "チョウ / は・る", "chou / ha-ru", "stretch, spread, strain", "主張 (shuchou - claim)", "テントを広場にしっかりと張る。", "てんとをひろばにしっかりとはる。", "Firmly pitch a tent in the plaza."],
  ["蔓", "マン / つる、はびこ・る", "man / tsuru, habiko-ru", "vine, spread, rampancy", "蔓延 (man'en - epidemic)", "蔦の蔓が壁を伝って伸びる。", "つたのつるがかべをつたってのびる。", "Ivy vines stretch along the wall."],
  ["延", "エン / の・びる、の・べる", "en / no-biru, no-beru", "prolong, extend, postpone", "延長 (enchou - extension)", "試合の時間が延長された。", "しあいのじかんがえんちょうされた。", "The match time was extended."],
  ["未", "ミ、ビ / いま・だ", "mi, bi / ima-da", "not yet, un-", "未来 (mirai - future)", "未曾有の困難に団結して立ち向かう。", "みぞうのこんなんにだんけつしてたちむかう。", "Confront unprecedented difficulties in solidarity."],
  ["曾", "ソウ、ゾウ / かつ・て", "sou, zou / katsu-te", "formerly, once, ever", "未曾有 (mizou - unexampled)", "未曾有の大記録を打ち立てる。", "みぞうのだいきろくをうちたてる。", "Establish an unprecedented grand record."],
  ["有", "ユウ、ウ / あ・る", "yuu, u / a-ru", "possess, exist, have", "有名 (yuumei - famous)", "世界的に有名な文化遺産。", "せかいてきにゆうめいなぶんかいさん。", "A globally famous cultural heritage."],
  ["名", "メイ、ミョウ / な", "mei, myou / na", "name, noted, prestige", "名残 (nagori - traces, sorrow of parting)", "別れの名残を惜しむ。", "わかれのなごりをおしむ。", "Reluctant to part in the sorrow of farewell."],
  ["残", "ザン / のこ・る", "zan / noko-ru", "remainder, leftover", "残念 (zannen - regrettable)", "雪が山頂に白く残っている。", "ゆきがさんちょうにしろくのこっている。", "Snow remains white on the mountain peak."],
  ["容", "ヨウ", "you", "contain", "容認 (younin - approval)", "不正な手段は断じて容認しない。", "ふせいなしゅだんはだんじてようにんしない。", "Unlawful methods are decidedly not tolerated."],
  ["認", "ニン", "nin", "recognize", "容認 (younin - toleration)", "多様な生き方を温かく認める。", "たようないきかたをあたたかくみとめる。", "Warmly recognize diverse ways of living."],
  ["抑", "ヨク / おさ・える", "yoku / osa-eru", "repress, push down", "抑制 (yokusei - inhibition)", "感情を高ぶらせず冷静に抑える。", "かんじょうをたかぶらせずれいせいにおさえる。", "Calmly restrain emotions without getting agitated."],
  ["律", "リツ", "ritsu", "law", "律速 (rissoku - rate-determining)", "全体の流れを律速する要因を突き止める。", "ぜんたいのながれをりっそくするよういんをつきとめる。", "Identify the factor that is rate-limiting the entire flow."],
  ["速", "ソク", "soku", "speed", "律速 (rissoku - rate-limiting)", "効率を最大化して速度を上げる。", "こうりつをさいだいかしてそくどをあげる。", "Maximize efficiency and increase speed."],
  ["累", "ルイ", "rui", "accumulate, involve", "累計 (ruikei - cumulative total)", "長年の累計実績が認められる。", "ながねんのるいけいじっせきがみとめられる。", "Cumulative track record over years is acknowledged."],
  ["計", "ケイ", "kei", "total, count", "累計 (ruikei - total)", "正確に統計データを集計する。", "せいかくにとうけいでーたをしゅうけいする。", "Accurately aggregate statistical data."],
  ["露", "ロ、ロウ / つゆ", "ro, rou / tsuyu", "dew, exposed, open", "露呈 (rotei - exposure)", "草の葉に朝露が輝いている。", "くさのはにあさつゆがかがやいている。", "Morning dew shines on the leaves of grass."],
  ["呈", "テイ", "tei", "display, offer, present", "進呈 (shintei - presentation)", "記念品を参加者に進呈する。", "きねんひんをさんかしゃにしんていする。", "Present commemorative gifts to participants."],
  ["矮", "ワイ", "wai", "low, dwarf, short", "矮小 (waishou - diminutive, petty)", "重大な問題を矮小化してはならない。", "じゅうだいなもんだいをわいしょうかしてはならない。", "Critical problems must not be minimized."],
  ["小", "ショウ / ちい・さい", "shou / chii-sai", "small, little", "矮小 (waishou - petty)", "小さな努力の積み重ねが偉業を生む。", "ちいさなどりょくのつみかさねがいぎょうをうむ。", "Accumulation of small efforts creates great achievements."],
  ["慶", "ケイ / よろこ・び", "kei / yoroko-bi", "jubilation, rejoice, congratulate", "慶事 (keiji - auspicious event)", "心からのお慶びを申し上げます。", "こころからのおよろこびをもうしあげます。", "I offer my heartfelt congratulations."],
  ["蔑", "ベツ / さげす・む", "betsu / sagesu-mu", "scorn, despise, contempt", "軽蔑 (keibetsu - contempt)", "努力する人を軽蔑してはならない。", "どりょくするひとをけいべつしてはならない。", "One must never despise a person who makes efforts."],
  ["遵", "ジュン", "jun", "abide by, follow, obey", "遵守 (junshu - compliance)", "社会通念と諸法令を厳格に遵守する。", "しゃかいつうねんとしょほうれいをげんかくにじゅんしゅする。", "Strictly comply with social norms and regulations."]
];

compileLevel('N1', n1Data, path.join(__dirname, '../data/kanji/n1.json'));
