const path = require('path');
const { compileLevel } = require('./kanji_compiler_helper');

const n2Data = [
  ["職", "ショク / そく", "shoku / soku", "post, employment, work", "職業 (shokugyou - occupation)", "専門的な知識を活かした職に就く。", "せんもんてきなちしきをいかしたしょくにつく。", "Get a job utilizing specialized knowledge."],
  ["容", "ヨウ / い・れる", "you / i-reru", "contain, form, looks", "内容 (naiyou - contents)", "書類の内容をしっかり把握する。", "しょるいのないようをしっかりはあくする。", "Firmly grasp the contents of the document."],
  ["演", "エン", "en", "performance, act, play", "演技 (engi - acting)", "舞台で見事な演技を披露する。", "ぶたいでみごとなえんぎをひろうする。", "Showcase superb acting on stage."],
  ["党", "トウ", "tou", "party, faction, clique", "政党 (seitou - political party)", "政党の基本政策を比較する。", "せいとうのきほんせいさくをひかくする。", "Compare basic policies of political parties."],
  ["規", "キ", "ki", "standard, measure", "規則 (kisoku - rule)", "安全基準の規則を遵守する。", "あんぜんきじゅんのきそくをじゅんしゅする。", "Comply with the regulations of safety standards."],
  ["得", "トク / え・る、う・る", "toku / e-ru, u-ru", "gain, get, profit", "納得 (nattoku - consent)", "貴重な経験と知見を得る。", "きちょうなけいけんとちけんをえる。", "Gain valuable experience and insights."],
  ["資", "シ", "shi", "assets, resources, capital", "資格 (shikaku - qualification)", "専門資格の取得に向けて猛勉強する。", "せんもんしかくのしゅとくにむけてもうべんきょうする。", "Study intensely towards acquiring specialized qualifications."],
  ["閣", "カク", "kaku", "tower, palace, cabinet", "内閣 (naikaku - cabinet)", "内閣の支持率が報道される。", "ないかくのしじりつがほうどうされる。", "The cabinet approval rating is reported."],
  ["官", "カン", "kan", "bureaucrat, the government", "官僚 (kanryou - bureaucrat)", "外交官として海外に赴任する。", "がいこうかんとしてかいがいにふにんする。", "Be posted overseas as a diplomat."],
  ["省", "ショウ、セイ / はぶ・く、かえり・みる", "shou, sei / habu-ku, kaeri-miru", "focus, government ministry, omit", "反省 (hansei - reflection)", "過去の失敗を真摯に反省する。", "かこのしっぱいにしんしにはんせいする。", "Sincerely reflect upon past mistakes."],
  ["責", "セキ / せ・める", "seki / se-meru", "blame, condemn, responsibility", "責任 (sekinin - responsibility)", "リーダーとしての責任を果たす。", "りーだーとしてのせきにんをはたす。", "Fulfill one's responsibility as a leader."],
  ["任", "ニン / まか・せる", "nin / maka-seru", "responsibility, duty, entrust", "任務 (ninmu - mission)", "重要な任務を任される。", "じゅうようなにんむをまかされる。", "Be entrusted with an important mission."],
  ["処", "ショ", "sho", "dispose, manage, deal with", "処理 (shori - processing)", "大量のデータを素早く処理する。", "たいりょうのでーたをすばやくしょりする。", "Quickly process large amounts of data."],
  ["貿", "ボウ", "bou", "trade, exchange", "貿易 (boueki - foreign trade)", "海外の企業と貿易を行う。", "かいがいのきぎょうとぼうえきをおこなう。", "Conduct trade with overseas enterprises."],
  ["防", "ボウ / ふせ・ぐ", "bou / fuse-gu", "ward off, defend, prevent", "防止 (boushi - prevention)", "事故の再発を未然に防ぐ。", "じこのさいはつをみぜんにふせぐ。", "Prevent recurrence of accidents beforehand."],
  ["補", "ホ / おぎな・う", "ho / ogina-u", "supplement, supply, assist", "補充 (hojuu - replenishment)", "不足している栄養を補う。", "ふそくしているえいようをおぎなう。", "Supplement lacking nutritional needs."],
  ["批", "ヒ", "hi", "criticism, strike", "批判 (hihan - criticism)", "建設的な批判を受け入れて改善する。", "けんせつてきなひはんをうけいれてかいぜんする。", "Accept constructive criticism to make improvements."],
  ["断", "ダン / た・つ、ことわ・る", "dan / ta-tsu, kotowa-ru", "sever, refuse, decision", "判断 (handan - judgment)", "冷静な判断を下す。", "れいせいなはんだんをくだす。", "Make a calm judgment."],
  ["導", "ドウ / みちび・く", "dou / michibi-ku", "guidance, leading, conduct", "指導 (shidou - leadership, guidance)", "初心者を親切に導く。", "しょしんしゃをしんせつにみちびく。", "Kindly guide beginners."],
  ["認", "ニン / みと・める", "nin / mito-meru", "acknowledge, witness, recognize", "確認 (kakunin - confirmation)", "努力の成果を正当に認める。", "どりょくのせいかをせいとうにみとめる。", "Rightly recognize the fruits of effort."],
  ["疑", "ギ / うたが・う", "gi / utaga-u", "doubt, distrust, be suspicious", "疑問 (gimon - question, doubt)", "真実について疑いを持つ。", "しんじつについてうたがいをもつ。", "Harbor doubts about the truth."],
  ["講", "コウ", "kou", "lecture, study", "講義 (kougi - lecture)", "大学で専門講義を熱心に聴く。", "だいがくでせんもんこうぎをねっしんにきく。", "Enthusiastically listen to specialized lectures at university."],
  ["義", "ギ", "gi", "justice, honor, loyalty", "正義 (seigi - justice)", "社会の正義を守るために行動する。", "しゃかいのせいぎをまもるためによりこうどうする。", "Act to protect justice in society."],
  ["論", "ロン", "ron", "argument, discourse, theory", "理論 (riron - theory)", "論理的な思考力を鍛える。", "ろんりてきなしこうりょくをきたえる。", "Train logical thinking ability."],
  ["討", "トウ / う・つ", "tou / u-tsu", "chastise, attack, discuss", "検討 (kentou - examination)", "改善案をチームで検討する。", "かいぜんあんをちーむでけんとうする。", "Examine improvement proposals in the team."],
  ["識", "シキ", "shiki", "discriminating, know, write", "知識 (chishiki - knowledge)", "豊かな専門知識を蓄える。", "ゆたかなせんもんちしきをたくわえる。", "Accumulate rich specialized knowledge."],
  ["境", "キョウ、ケイ / さかい", "kyou, kei / sakai", "boundary, border, region", "環境 (kankyou - environment)", "自然環境を後世に残す。", "しぜんかんきょうをこうせいにのこす。", "Leave natural environment for future generations."],
  ["態", "タイ / わざ・と", "tai / waza-to", "attitude, condition, appearance", "態度 (taido - attitude)", "誠実な態度で人と接する。", "せいじつなたいどでひととせっする。", "Interact with people with a sincere attitude."],
  ["勢", "セイ / いきお・い", "sei / ikio-i", "forces, energy, vigor", "姿勢 (shisei - posture, attitude)", "前向きな姿勢で困難に立ち向かう。", "まえむきなしせいでこんなんにたちむかう。", "Confront difficulties with a forward-looking attitude."],
  ["総", "ソウ / す・べて", "sou / su-bete", "general, whole, all", "総合 (sougou - synthesis)", "総合的な判断が求められる。", "そうごうてきなはんだんがもとめられる。", "Comprehensive judgment is required."],
  ["設", "セツ / もう・ける", "setsu / mou-keru", "establishment, provision", "施設 (shisetsu - facility)", "地域に新しい公共施設を建設する。", "ちいきにあたらしいこうきょうしせつをけんせつする。", "Construct new public facilities in the area."],
  ["計", "ケイ / はか・る", "kei / haka-ru", "plot, plan, measure", "計画 (keikaku - plan)", "綿密な旅行計画を立てる。", "めんみつなりょこうけいかくをたてる。", "Formulate a meticulous travel plan."],
  ["画", "ガ、カク / えが・く", "ga, kaku / ega-ku", "brush-stroke, picture", "映画 (eiga - movie)", "将来の人生設計を企画する。", "しょうらいのじんせいせっけいをきかくする。", "Plan one's future life design."],
  ["案", "アン", "an", "plan, suggestion, draft", "提案 (teian - proposal)", "業務効率化のための妙案を出す。", "ぎょうむこうりつかのためのみょうあんをだす。", "Put forward an ingenious proposal for efficiency."],
  ["提", "テイ / さ・げる", "tei / sa-geru", "propose, take in hand", "提出 (teishutsu - submission)", "レポートを期限までに提出する。", "れぽーとをきげんまでにていしゅつする。", "Submit the report by the deadline."],
  ["供", "キョウ、ク / とも、そな・える", "kyou, ku / tomo, sona-eru", "submit, offer, accompany", "提供 (teikyou - provision)", "高品質なサービスを提供する。", "こうひんしつなさーびすをていきょうする。", "Provide high quality services."],
  ["標", "ヒョウ / しるし", "hyou / shirushi", "signpost, mark, target", "目標 (mokuhyou - goal)", "目標に向かって日々前進する。", "もくひょうにむかってひびぜんしんする。", "Move forward daily towards goals."],
  ["創", "ソウ / つく・る", "sou / tsuku-ru", "create, originate, establish", "創造 (souzou - creation)", "独創的なアイデアを形にする。", "どくそうてきなあいであをかたちにする。", "Turn creative ideas into tangible form."],
  ["訪", "ホウ / おとず・れる", "hou / otozu-reru", "visit, call on", "訪問 (houmon - visit)", "海外の提携先を訪問する。", "かいがいのていけいさきをほうもんする。", "Visit overseas partner organizations."],
  ["景", "ケイ", "kei", "scenery, view", "景色 (keshiki - scenery)", "展望台から素晴らしい夜景を眺める。", "てんぼうだいからすばらしいやけいをながめる。", "Gaze upon a splendid night view from the observatory."],
  ["況", "キョウ / まし・て", "kyou / mashi-te", "condition, situation", "状況 (joukyou - situation)", "現在の状況を冷静に分析する。", "げんざいのじょうきょうをれいせいにぶんせきする。", "Analyze the current situation calmly."],
  ["態", "タイ", "tai", "condition, state", "状態 (joutai - condition)", "健康な状態を長く保つ。", "けんこうなじょうたいをながくたもつ。", "Maintain healthy condition for a long time."],
  ["容", "ヨウ", "you", "capacity, looks", "容易 (youi - easy, simple)", "容易に解決できる問題ではない。", "よういにかいけつできるもんだいではない。", "It is not a problem that can be easily solved."],
  ["構", "コウ / かま・える", "kou / kama-eru", "structure, construct, posture", "構造 (kouzou - structure)", "建物の耐震構造を強化する。", "たてもののたいしんこうぞうをきょうかする。", "Reinforce earthquake-resistant structure of the building."],
  ["造", "ゾウ / つく・る", "zou / tsuku-ru", "create, make, build", "製造 (seizou - manufacturing)", "日本のものづくり精神を尊重する。", "にほんのものづくりせいしんをそんちょうする。", "Respect the spirit of Japanese craftsmanship."],
  ["模", "モ、ボ", "mo, bo", "imitation, copy, mock", "規模 (kibo - scale)", "大規模な国際会議が開催される。", "だいきぼなこくさいかいぎがかいさいされる。", "A large-scale international conference is held."],
  ["範", "ハン", "han", "pattern, example, model", "模範 (mohan - model, exemplar)", "模範的な行動を心がける。", "もはんてきなこうどうをこころがける。", "Keep exemplary behavior in mind."],
  ["域", "イキ", "iki", "range, region, limits", "地域 (chiiki - region, local)", "地域社会に貢献する活動を行う。", "ちいきしゃかいにこうけんするかつどうをおこなう。", "Engage in activities contributing to local community."],
  ["拡", "カク / ひろ・がる", "kaku / hiro-garu", "broaden, extend, expand", "拡大 (kakudai - expansion)", "事業の規模を海外へ拡大する。", "じぎょうのきぼをかいがいへかくだいする。", "Expand business operations abroad."],
  ["縮", "シュク / ちぢ・む", "shuku / chiji-mu", "shrink, contract, reduce", "短縮 (tanshuku - shortening)", "移動時間を大幅に短縮する。", "いどうじかんをおおはばにたんしゅくする。", "Significantly shorten transit time."],
  ["優", "ユウ / やさ・しい、すぐ・れる", "yuu / yasa-shii, sugu-reru", "superior, gentle, excel", "優秀 (yuushuu - excellent)", "人に優しく接する温かい心。", "ひとにやさしくせっするあたたかいこころ。", "A warm heart that treats others gently."],
  ["秀", "シュウ / ひい・でる", "shuu / hii-deru", "surpass, excel, beauty", "優秀 (yuushuu - excellence)", "秀でた才能を磨く。", "ひいでたさいのうをみがく。", "Polish one's outstanding talent."],
  ["劣", "レツ / おと・る", "retsu / oto-ru", "inferiority, be inferior", "劣等感 (rettoukan - inferiority complex)", "他人に劣らぬ熱意を持つ。", "たにんにおとらぬねついをもつ。", "Have enthusiasm second to none."],
  ["充", "ジュウ / あ・てる", "juu / a-teru", "allot, fill", "充実 (juujitsu - fulfillment)", "充実した毎日を過ごす。", "じゅうじつしたまいにちをすごす。", "Spend every day in fulfillment."],
  ["乏", "ボウ / とぼ・しい", "bou / tobo-shii", "destitution, scarce, lack", "貧乏 (binbou - poor)", "経験が乏しい時期を乗り越える。", "けいけんがとぼしいじきをのりこえる。", "Overcome the period of scarce experience."],
  ["富", "フ、フウ / と・む、とみ", "fu, fuu / to-mu, tomi", "wealth, enrich, abundant", "豊富 (houfu - abundant)", "豊富な知識を持つ専門家。", "ほうふなちしきをもつせんもんか。", "An expert with abundant knowledge."],
  ["貧", "ヒン、ビン / まず・しい", "hin, bin / mazu-shii", "poverty, poor", "貧困 (hinkon - poverty)", "世界の貧困問題を考える。", "せかいのひんこんもんだいをかんがえる。", "Contemplate the world's poverty problems."],
  ["純", "ジュン", "jun", "genuine, purity, innocent", "純粋 (junsui - pure)", "純粋な心で学問に向き合う。", "じゅんすいなこころでがくもんにむきあう。", "Approach academia with a pure heart."],
  ["粋", "スイ / いき", "sui / iki", "chic, style, purity", "純粋 (junsui - genuine)", "日本の粋な文化を嗜む。", "にほんのいきなぶんかをたしなむ。", "Enjoy stylish and chic Japanese culture."],
  ["粗", "ソ / あら・い", "so / ara-i", "coarse, rough, crude", "粗大 (sodai - bulky)", "粗末に扱わず大切に使う。", "そまつにあつかわずたいせつにつかう。", "Use carefully without treating crudely."],
  ["精", "セイ、ショウ", "sei, shou", "refined, ghost, fairy, energy", "精神 (seishin - spirit, mind)", "不屈の精神で努力を重ねる。", "ふくつのせいしんでどりょくをかさねる。", "Stack up effort with an indomitable spirit."],
  ["神", "シン、ジン / かみ", "shin, jin / kami", "gods, mind, soul", "神社 (jinja - Shinto shrine)", "初詣で神社に参拝する。", "はつもうででじんじゃにさんぱいする。", "Worship at a shrine during New Year's visit."]
];

compileLevel('N2', n2Data, path.join(__dirname, '../data/kanji/n2.json'));
